<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/address.proto

namespace GPBMetadata\Types\V1;

class Address
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFC\x01\x0A\x16types/v1/address.proto\x12\x08types.v1\"\x95\x01\x0A\x07Address\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\x12\x16\x0A\x06street\x18\x02 \x01(\x09R\x06street\x12\x1F\x0A\x0Bpostal_code\x18\x03 \x01(\x09R\x0ApostalCode\x12\x1A\x0A\x08locality\x18\x04 \x01(\x09R\x08locality\x12!\x0A\x0Ccountry_code\x18\x05 \x01(\x09R\x0BcountryCodeB8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

