<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/date.proto

namespace GPBMetadata\Types\V1;

class Date
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x01\x0A\x13types/v1/date.proto\x12\x08types.v1\"B\x0A\x04Date\x12\x10\x0A\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\x0A\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\x0A\x04year\x18\x03 \x01(\x05R\x04yearB8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

