<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/error.proto

namespace GPBMetadata\Types\V1;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x01\x0A\x14types/v1/error.proto\x12\x08types.v1\"K\x0A\x0BErrorDetail\x12\x1D\x0A\x0Aerror_code\x18\x01 \x01(\x09R\x09errorCode\x12\x1D\x0A\x0Aerror_text\x18\x02 \x01(\x09R\x09errorText\"B\x0A\x0FErrorAttachment\x12/\x0A\x07details\x18\x01 \x03(\x0B2\x15.types.v1.ErrorDetailR\x07detailsB8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

