<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/money.proto

namespace GPBMetadata\Types\V1;

class Money
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x01\x0A\x14types/v1/money.proto\x12\x08types.v1\"D\x0A\x05Money\x12#\x0A\x0Dcurrency_code\x18\x01 \x01(\x09R\x0CcurrencyCode\x12\x16\x0A\x06amount\x18\x03 \x01(\x01R\x06amountB8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

