<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/pagination.proto

namespace GPBMetadata\Types\V1;

class Pagination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x01\x0A\x19types/v1/pagination.proto\x12\x08types.v1\"A\x0A\x0AOffsetPage\x12\x16\x0A\x06number\x18\x01 \x01(\x0DR\x06number\x12\x1B\x0A\x09page_size\x18\x02 \x01(\x0DR\x08pageSize\"(\x0A\x10OffsetPageResult\x12\x14\x0A\x05total\x18\x01 \x01(\x0DR\x05totalB8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

