<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace GPBMetadata\Types\V1;

class Shipping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Types\V1\Money::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x99\x05\x0A\x17types/v1/shipping.proto\x12\x08types.v1\"k\x0A\x0EShippingMethod\x12\x1D\x0A\x09is_pickup\x18\x01 \x01(\x08H\x00R\x08isPickup\x120\x0A\x08shipment\x18\x02 \x01(\x0B2\x12.types.v1.ShipmentH\x00R\x08shipmentB\x08\x0A\x06method\"\xA3\x01\x0A\x08Shipment\x12G\x0A\x11shipment_provider\x18\x01 \x01(\x0E2\x1A.types.v1.ShipmentProviderR\x10shipmentProvider\x12%\x0A\x05price\x18\x02 \x01(\x0B2\x0F.types.v1.MoneyR\x05price\x12'\x0A\x0Ftracking_number\x18\x03 \x01(\x09R\x0EtrackingNumber*\x9E\x02\x0A\x10ShipmentProvider\x12!\x0A\x1DSHIPMENT_PROVIDER_UNSPECIFIED\x10\x00\x12#\x0A\x1FSHIPMENT_PROVIDER_DEUTSCHE_POST\x10\x01\x12\x19\x0A\x15SHIPMENT_PROVIDER_DHL\x10\x02\x12\x1C\x0A\x18SHIPMENT_PROVIDER_HERMES\x10\x03\x12\x19\x0A\x15SHIPMENT_PROVIDER_DPD\x10\x04\x12\x19\x0A\x15SHIPMENT_PROVIDER_UPS\x10\x05\x12\x19\x0A\x15SHIPMENT_PROVIDER_GLS\x10\x06\x12\x1B\x0A\x17SHIPMENT_PROVIDER_FEDEX\x10\x07\x12\x1B\x0A\x17SHIPMENT_PROVIDER_OTHER\x10\x08B8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

