<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace GPBMetadata\Types\V1;

class Shipping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Type\Money::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBF\x04\x0A\x17types/v1/shipping.proto\x12\x08types.v1\"j\x0A\x0EShippingMethod\x12\x1C\x0A\x08pickuped\x18\x01 \x01(\x08H\x00R\x08pickuped\x120\x0A\x08shipment\x18\x02 \x01(\x0B2\x12.types.v1.ShipmentH\x00R\x08shipmentB\x08\x0A\x06method\"\x99\x01\x0A\x08Shipment\x12+\x0A\x07carrier\x18\x01 \x01(\x0E2\x11.types.v1.CarrierR\x07carrier\x127\x0A\x0Dshipping_cost\x18\x02 \x01(\x0B2\x12.google.type.MoneyR\x0CshippingCost\x12'\x0A\x0Ftracking_number\x18\x03 \x01(\x09R\x0EtrackingNumber*\xCF\x01\x0A\x07Carrier\x12\x17\x0A\x13CARRIER_UNSPECIFIED\x10\x00\x12\x19\x0A\x15CARRIER_DEUTSCHE_POST\x10\x01\x12\x0F\x0A\x0BCARRIER_DHL\x10\x02\x12\x12\x0A\x0ECARRIER_HERMES\x10\x03\x12\x0F\x0A\x0BCARRIER_DPD\x10\x04\x12\x0F\x0A\x0BCARRIER_UPS\x10\x05\x12\x0F\x0A\x0BCARRIER_GLS\x10\x06\x12\x11\x0A\x0DCARRIER_FEDEX\x10\x07\x12\x12\x0A\x0ECARRIER_AMAZON\x10\x08\x12\x11\x0A\x0DCARRIER_OTHER\x10\x09B8Z6github.com/dudochnicht/proto-gen-go/typespb/v1;typespbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

