<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.CreateDeviceRequest</code>
 */
class CreateDeviceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     */
    protected $model_id = '';
    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     */
    protected $serial_number = null;
    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 4 [json_name = "manufactureDate"];</code>
     */
    protected $manufacture_date = null;
    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     */
    protected $transaction_ids = null;
    /**
     * Generated from protobuf field <code>int32 unit_number = 6 [json_name = "unitNumber"];</code>
     */
    protected $unit_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $model_id
     *     @type string $serial_number
     *     @type \Types\V1\Date $manufacture_date
     *     @type \Device\V1\TransactionIds $transaction_ids
     *     @type int $unit_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 1 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 1 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Device\V1\DeviceStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     * @return string
     */
    public function getModelId()
    {
        return $this->model_id;
    }

    /**
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     * @param string $var
     * @return $this
     */
    public function setModelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return isset($this->serial_number) ? $this->serial_number : '';
    }

    public function hasSerialNumber()
    {
        return isset($this->serial_number);
    }

    public function clearSerialNumber()
    {
        unset($this->serial_number);
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 4 [json_name = "manufactureDate"];</code>
     * @return \Types\V1\Date|null
     */
    public function getManufactureDate()
    {
        return $this->manufacture_date;
    }

    public function hasManufactureDate()
    {
        return isset($this->manufacture_date);
    }

    public function clearManufactureDate()
    {
        unset($this->manufacture_date);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 4 [json_name = "manufactureDate"];</code>
     * @param \Types\V1\Date $var
     * @return $this
     */
    public function setManufactureDate($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Date::class);
        $this->manufacture_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     * @return \Device\V1\TransactionIds|null
     */
    public function getTransactionIds()
    {
        return $this->transaction_ids;
    }

    public function hasTransactionIds()
    {
        return isset($this->transaction_ids);
    }

    public function clearTransactionIds()
    {
        unset($this->transaction_ids);
    }

    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     * @param \Device\V1\TransactionIds $var
     * @return $this
     */
    public function setTransactionIds($var)
    {
        GPBUtil::checkMessage($var, \Device\V1\TransactionIds::class);
        $this->transaction_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 6 [json_name = "unitNumber"];</code>
     * @return int
     */
    public function getUnitNumber()
    {
        return $this->unit_number;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 6 [json_name = "unitNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setUnitNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_number = $var;

        return $this;
    }

}

