<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.GetDeviceResponse</code>
 */
class GetDeviceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .device.v1.Device device = 1 [json_name = "device"];</code>
     */
    private $device;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\V1\Device[] $device
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .device.v1.Device device = 1 [json_name = "device"];</code>
     * @return RepeatedField<\Device\V1\Device>
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * Generated from protobuf field <code>repeated .device.v1.Device device = 1 [json_name = "device"];</code>
     * @param \Device\V1\Device[] $var
     * @return $this
     */
    public function setDevice($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Device\V1\Device::class);
        $this->device = $arr;

        return $this;
    }

}

