<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.ListModelDevicesRequest</code>
 */
class ListModelDevicesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string model_id = 1 [json_name = "modelId"];</code>
     */
    protected $model_id = '';
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model_id
     *     @type \Types\V1\OffsetPage $page
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string model_id = 1 [json_name = "modelId"];</code>
     * @return string
     */
    public function getModelId()
    {
        return $this->model_id;
    }

    /**
     * Generated from protobuf field <code>string model_id = 1 [json_name = "modelId"];</code>
     * @param string $var
     * @return $this
     */
    public function setModelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     * @return \Types\V1\OffsetPage|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     * @param \Types\V1\OffsetPage $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPage::class);
        $this->page = $var;

        return $this;
    }

}

