<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.ListPurchasedDevicesResponse</code>
 */
class ListPurchasedDevicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .device.v1.Device devices = 1 [json_name = "devices"];</code>
     */
    private $devices;
    /**
     * Key = TransactionID, Value = Transactions
     *
     * Generated from protobuf field <code>map<string, .transaction.v1.Transaction> transactions = 2 [json_name = "transactions"];</code>
     */
    private $transactions;
    /**
     * Key = ModelID, Value = DeviceName (Brand + Serie + Model)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 3 [json_name = "deviceNames"];</code>
     */
    private $device_names;
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 4 [json_name = "pageResult"];</code>
     */
    protected $page_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\V1\Device[] $devices
     *     @type array|\Google\Protobuf\Internal\MapField $transactions
     *           Key = TransactionID, Value = Transactions
     *     @type array|\Google\Protobuf\Internal\MapField $device_names
     *           Key = ModelID, Value = DeviceName (Brand + Serie + Model)
     *     @type \Types\V1\OffsetPageResult $page_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .device.v1.Device devices = 1 [json_name = "devices"];</code>
     * @return RepeatedField<\Device\V1\Device>
     */
    public function getDevices()
    {
        return $this->devices;
    }

    /**
     * Generated from protobuf field <code>repeated .device.v1.Device devices = 1 [json_name = "devices"];</code>
     * @param \Device\V1\Device[] $var
     * @return $this
     */
    public function setDevices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Device\V1\Device::class);
        $this->devices = $arr;

        return $this;
    }

    /**
     * Key = TransactionID, Value = Transactions
     *
     * Generated from protobuf field <code>map<string, .transaction.v1.Transaction> transactions = 2 [json_name = "transactions"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Key = TransactionID, Value = Transactions
     *
     * Generated from protobuf field <code>map<string, .transaction.v1.Transaction> transactions = 2 [json_name = "transactions"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\V1\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Key = ModelID, Value = DeviceName (Brand + Serie + Model)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 3 [json_name = "deviceNames"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getDeviceNames()
    {
        return $this->device_names;
    }

    /**
     * Key = ModelID, Value = DeviceName (Brand + Serie + Model)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 3 [json_name = "deviceNames"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setDeviceNames($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\DeviceName::class);
        $this->device_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 4 [json_name = "pageResult"];</code>
     * @return \Types\V1\OffsetPageResult|null
     */
    public function getPageResult()
    {
        return $this->page_result;
    }

    public function hasPageResult()
    {
        return isset($this->page_result);
    }

    public function clearPageResult()
    {
        unset($this->page_result);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 4 [json_name = "pageResult"];</code>
     * @param \Types\V1\OffsetPageResult $var
     * @return $this
     */
    public function setPageResult($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPageResult::class);
        $this->page_result = $var;

        return $this;
    }

}

