<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.UpdateServiceDataRequest</code>
 */
class UpdateServiceDataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>optional string serial_number = 2 [json_name = "serialNumber"];</code>
     */
    protected $serial_number = null;
    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 3 [json_name = "manufactureDate"];</code>
     */
    protected $manufacture_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type string $serial_number
     *     @type \Types\V1\Date $manufacture_date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 2 [json_name = "serialNumber"];</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return isset($this->serial_number) ? $this->serial_number : '';
    }

    public function hasSerialNumber()
    {
        return isset($this->serial_number);
    }

    public function clearSerialNumber()
    {
        unset($this->serial_number);
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 2 [json_name = "serialNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 3 [json_name = "manufactureDate"];</code>
     * @return \Types\V1\Date|null
     */
    public function getManufactureDate()
    {
        return $this->manufacture_date;
    }

    public function hasManufactureDate()
    {
        return isset($this->manufacture_date);
    }

    public function clearManufactureDate()
    {
        unset($this->manufacture_date);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufacture_date = 3 [json_name = "manufactureDate"];</code>
     * @param \Types\V1\Date $var
     * @return $this
     */
    public function setManufactureDate($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Date::class);
        $this->manufacture_date = $var;

        return $this;
    }

}

