<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.UpdateUnitNumberRequest</code>
 */
class UpdateUnitNumberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>int32 unit_number = 2 [json_name = "unitNumber"];</code>
     */
    protected $unit_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $unit_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 2 [json_name = "unitNumber"];</code>
     * @return int
     */
    public function getUnitNumber()
    {
        return $this->unit_number;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 2 [json_name = "unitNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setUnitNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_number = $var;

        return $this;
    }

}

