<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device.proto

namespace Device\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>device.v1.UpdateDeviceRequest</code>
 */
class UpdateDeviceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     */
    protected $serial_number = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp manufacture_date = 4 [json_name = "manufactureDate"];</code>
     */
    protected $manufacture_date = null;
    /**
     * Generated from protobuf field <code>int32 unit_number = 5 [json_name = "unitNumber"];</code>
     */
    protected $unit_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type int $status
     *     @type string $serial_number
     *     @type \Google\Protobuf\Timestamp $manufacture_date
     *     @type int $unit_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Device\V1\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 2 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.device.v1.DeviceStatus status = 2 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Device\V1\DeviceStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return isset($this->serial_number) ? $this->serial_number : '';
    }

    public function hasSerialNumber()
    {
        return isset($this->serial_number);
    }

    public function clearSerialNumber()
    {
        unset($this->serial_number);
    }

    /**
     * Generated from protobuf field <code>optional string serial_number = 3 [json_name = "serialNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp manufacture_date = 4 [json_name = "manufactureDate"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getManufactureDate()
    {
        return $this->manufacture_date;
    }

    public function hasManufactureDate()
    {
        return isset($this->manufacture_date);
    }

    public function clearManufactureDate()
    {
        unset($this->manufacture_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp manufacture_date = 4 [json_name = "manufactureDate"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setManufactureDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->manufacture_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 5 [json_name = "unitNumber"];</code>
     * @return int
     */
    public function getUnitNumber()
    {
        return $this->unit_number;
    }

    /**
     * Generated from protobuf field <code>int32 unit_number = 5 [json_name = "unitNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setUnitNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_number = $var;

        return $this;
    }

}

