<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device_service.proto

namespace GPBMetadata\Device\V1;

class DeviceService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Device\V1\Device::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFF\x04\x0A\x1Edevice/v1/device_service.proto\x12\x09device.v12\x8D\x04\x0A\x0DDeviceService\x12a\x0A\x12ListDevicesByModel\x12\$.device.v1.ListDevicesByModelRequest\x1A%.device.v1.ListDevicesByModelResponse\x12^\x0A\x11ListLatestDevices\x12#.device.v1.ListLatestDevicesRequest\x1A\$.device.v1.ListLatestDevicesResponse\x12F\x0A\x09GetDevice\x12\x1B.device.v1.GetDeviceRequest\x1A\x1C.device.v1.GetDeviceResponse\x12O\x0A\x0CCreateDevice\x12\x1E.device.v1.CreateDeviceRequest\x1A\x1F.device.v1.CreateDeviceResponse\x12O\x0A\x0CUpdateDevice\x12\x1E.device.v1.UpdateDeviceRequest\x1A\x1F.device.v1.UpdateDeviceResponse\x12O\x0A\x0CDeleteDevice\x12\x1E.device.v1.DeleteDeviceRequest\x1A\x1F.device.v1.DeleteDeviceResponseB:Z8github.com/dudochnicht/proto-gen-go/devicepb/v1;devicepbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

