<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/v1/device_service.proto

namespace GPBMetadata\Device\V1;

class DeviceService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Device\V1\Device::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x07\x0A\x1Edevice/v1/device_service.proto\x12\x09device.v12\xF5\x06\x0A\x0DDeviceService\x12L\x0A\x0BListDevices\x12\x1D.device.v1.ListDevicesRequest\x1A\x1E.device.v1.ListDevicesResponse\x12[\x0A\x10ListModelDevices\x12\".device.v1.ListModelDevicesRequest\x1A#.device.v1.ListModelDevicesResponse\x12X\x0A\x0FListSoldDevices\x12!.device.v1.ListSoldDevicesRequest\x1A\".device.v1.ListSoldDevicesResponse\x12g\x0A\x14ListPurchasedDevices\x12&.device.v1.ListPurchasedDevicesRequest\x1A'.device.v1.ListPurchasedDevicesResponse\x12F\x0A\x09GetDevice\x12\x1B.device.v1.GetDeviceRequest\x1A\x1C.device.v1.GetDeviceResponse\x12O\x0A\x0CCreateDevice\x12\x1E.device.v1.CreateDeviceRequest\x1A\x1F.device.v1.CreateDeviceResponse\x12O\x0A\x0CUpdateStatus\x12\x1E.device.v1.UpdateStatusRequest\x1A\x1F.device.v1.UpdateStatusResponse\x12^\x0A\x11UpdateServiceData\x12#.device.v1.UpdateServiceDataRequest\x1A\$.device.v1.UpdateServiceDataResponse\x12[\x0A\x10UpdateUnitNumber\x12\".device.v1.UpdateUnitNumberRequest\x1A#.device.v1.UpdateUnitNumberResponse\x12O\x0A\x0CDeleteDevice\x12\x1E.device.v1.DeleteDeviceRequest\x1A\x1F.device.v1.DeleteDeviceResponseB:Z8github.com/dudochnicht/proto-gen-go/devicepb/v1;devicepbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

