<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/address.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string street = 2 [json_name = "street"];</code>
     */
    protected $street = '';
    /**
     * Generated from protobuf field <code>string postal_code = 3 [json_name = "postalCode"];</code>
     */
    protected $postal_code = '';
    /**
     * Generated from protobuf field <code>string locality = 4 [json_name = "locality"];</code>
     */
    protected $locality = '';
    /**
     * Generated from protobuf field <code>string country_code = 5 [json_name = "countryCode"];</code>
     */
    protected $country_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $street
     *     @type string $postal_code
     *     @type string $locality
     *     @type string $country_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Address::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street = 2 [json_name = "street"];</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Generated from protobuf field <code>string street = 2 [json_name = "street"];</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 3 [json_name = "postalCode"];</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 3 [json_name = "postalCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string locality = 4 [json_name = "locality"];</code>
     * @return string
     */
    public function getLocality()
    {
        return $this->locality;
    }

    /**
     * Generated from protobuf field <code>string locality = 4 [json_name = "locality"];</code>
     * @param string $var
     * @return $this
     */
    public function setLocality($var)
    {
        GPBUtil::checkString($var, True);
        $this->locality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country_code = 5 [json_name = "countryCode"];</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * Generated from protobuf field <code>string country_code = 5 [json_name = "countryCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_code = $var;

        return $this;
    }

}

