<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace Types\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.v1.Carrier</code>
 */
class Carrier
{
    /**
     * Generated from protobuf enum <code>CARRIER_UNSPECIFIED = 0;</code>
     */
    const CARRIER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CARRIER_DEUTSCHE_POST = 1;</code>
     */
    const CARRIER_DEUTSCHE_POST = 1;
    /**
     * Generated from protobuf enum <code>CARRIER_DHL = 2;</code>
     */
    const CARRIER_DHL = 2;
    /**
     * Generated from protobuf enum <code>CARRIER_HERMES = 3;</code>
     */
    const CARRIER_HERMES = 3;
    /**
     * Generated from protobuf enum <code>CARRIER_DPD = 4;</code>
     */
    const CARRIER_DPD = 4;
    /**
     * Generated from protobuf enum <code>CARRIER_UPS = 5;</code>
     */
    const CARRIER_UPS = 5;
    /**
     * Generated from protobuf enum <code>CARRIER_GLS = 6;</code>
     */
    const CARRIER_GLS = 6;
    /**
     * Generated from protobuf enum <code>CARRIER_FEDEX = 7;</code>
     */
    const CARRIER_FEDEX = 7;
    /**
     * Generated from protobuf enum <code>CARRIER_AMAZON = 8;</code>
     */
    const CARRIER_AMAZON = 8;
    /**
     * Generated from protobuf enum <code>CARRIER_OTHER = 9;</code>
     */
    const CARRIER_OTHER = 9;

    private static $valueToName = [
        self::CARRIER_UNSPECIFIED => 'CARRIER_UNSPECIFIED',
        self::CARRIER_DEUTSCHE_POST => 'CARRIER_DEUTSCHE_POST',
        self::CARRIER_DHL => 'CARRIER_DHL',
        self::CARRIER_HERMES => 'CARRIER_HERMES',
        self::CARRIER_DPD => 'CARRIER_DPD',
        self::CARRIER_UPS => 'CARRIER_UPS',
        self::CARRIER_GLS => 'CARRIER_GLS',
        self::CARRIER_FEDEX => 'CARRIER_FEDEX',
        self::CARRIER_AMAZON => 'CARRIER_AMAZON',
        self::CARRIER_OTHER => 'CARRIER_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

