<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/date.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.Date</code>
 */
class Date extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 day = 1 [json_name = "day"];</code>
     */
    protected $day = 0;
    /**
     * Generated from protobuf field <code>int32 month = 2 [json_name = "month"];</code>
     */
    protected $month = 0;
    /**
     * Generated from protobuf field <code>int32 year = 3 [json_name = "year"];</code>
     */
    protected $year = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $day
     *     @type int $month
     *     @type int $year
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Date::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 day = 1 [json_name = "day"];</code>
     * @return int
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>int32 day = 1 [json_name = "day"];</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 month = 2 [json_name = "month"];</code>
     * @return int
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * Generated from protobuf field <code>int32 month = 2 [json_name = "month"];</code>
     * @param int $var
     * @return $this
     */
    public function setMonth($var)
    {
        GPBUtil::checkInt32($var);
        $this->month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 3 [json_name = "year"];</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 3 [json_name = "year"];</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

}

