<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/error.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ErrorDetail is a backend-internal "sub-error". Each error can have one or
 * more details attached (see `ErrorAttachment`). To reconstruct these errors
 * we need to have the error code and the error message.
 *
 * Generated from protobuf message <code>types.v1.ErrorDetail</code>
 */
class ErrorDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * The error code of the sub-error.
     *
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     */
    protected $error_code = '';
    /**
     * The error text of the sub-error (for devs).
     *
     * Generated from protobuf field <code>string error_text = 2 [json_name = "errorText"];</code>
     */
    protected $error_text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error_code
     *           The error code of the sub-error.
     *     @type string $error_text
     *           The error text of the sub-error (for devs).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * The error code of the sub-error.
     *
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * The error code of the sub-error.
     *
     * Generated from protobuf field <code>string error_code = 1 [json_name = "errorCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_code = $var;

        return $this;
    }

    /**
     * The error text of the sub-error (for devs).
     *
     * Generated from protobuf field <code>string error_text = 2 [json_name = "errorText"];</code>
     * @return string
     */
    public function getErrorText()
    {
        return $this->error_text;
    }

    /**
     * The error text of the sub-error (for devs).
     *
     * Generated from protobuf field <code>string error_text = 2 [json_name = "errorText"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorText($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_text = $var;

        return $this;
    }

}

