<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/error.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ErrorAttachment contains the details for a single error. See `ClientErrorAttachment`
 * for more details.
 *
 * Generated from protobuf message <code>types.v1.ErrorAttachment</code>
 */
class ErrorAttachment extends \Google\Protobuf\Internal\Message
{
    /**
     * Details for each error that happened (empty for single error).
     *
     * Generated from protobuf field <code>repeated .types.v1.ErrorDetail details = 1 [json_name = "details"];</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\V1\ErrorDetail[] $details
     *           Details for each error that happened (empty for single error).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * Details for each error that happened (empty for single error).
     *
     * Generated from protobuf field <code>repeated .types.v1.ErrorDetail details = 1 [json_name = "details"];</code>
     * @return RepeatedField<\Types\V1\ErrorDetail>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Details for each error that happened (empty for single error).
     *
     * Generated from protobuf field <code>repeated .types.v1.ErrorDetail details = 1 [json_name = "details"];</code>
     * @param \Types\V1\ErrorDetail[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\V1\ErrorDetail::class);
        $this->details = $arr;

        return $this;
    }

}

