<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/money.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Represents an amount of money with its currency type.
 *
 * Generated from protobuf message <code>types.v1.Money</code>
 */
class Money extends \Google\Protobuf\Internal\Message
{
    /**
     * The three-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     */
    protected $currency_code = '';
    /**
     * The Amount can be positive or negative
     *
     * Generated from protobuf field <code>double amount = 3 [json_name = "amount"];</code>
     */
    protected $amount = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currency_code
     *           The three-letter currency code defined in ISO 4217.
     *     @type float $amount
     *           The Amount can be positive or negative
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Money::initOnce();
        parent::__construct($data);
    }

    /**
     * The three-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     * The three-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>string currency_code = 1 [json_name = "currencyCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

    /**
     * The Amount can be positive or negative
     *
     * Generated from protobuf field <code>double amount = 3 [json_name = "amount"];</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * The Amount can be positive or negative
     *
     * Generated from protobuf field <code>double amount = 3 [json_name = "amount"];</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

}

