<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/pagination.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.OffsetPage</code>
 */
class OffsetPage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 number = 1 [json_name = "number"];</code>
     */
    protected $number = 0;
    /**
     * Generated from protobuf field <code>uint32 page_size = 2 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $number
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Pagination::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 number = 1 [json_name = "number"];</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>uint32 number = 1 [json_name = "number"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 page_size = 2 [json_name = "pageSize"];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>uint32 page_size = 2 [json_name = "pageSize"];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->page_size = $var;

        return $this;
    }

}

