<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/pagination.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.OffsetPageResult</code>
 */
class OffsetPageResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Pagination::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;

        return $this;
    }

}

