<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace Types\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.v1.ShipmentProvider</code>
 */
class ShipmentProvider
{
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_UNSPECIFIED = 0;</code>
     */
    const SHIPMENT_PROVIDER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_DEUTSCHE_POST = 1;</code>
     */
    const SHIPMENT_PROVIDER_DEUTSCHE_POST = 1;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_DHL = 2;</code>
     */
    const SHIPMENT_PROVIDER_DHL = 2;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_HERMES = 3;</code>
     */
    const SHIPMENT_PROVIDER_HERMES = 3;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_DPD = 4;</code>
     */
    const SHIPMENT_PROVIDER_DPD = 4;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_UPS = 5;</code>
     */
    const SHIPMENT_PROVIDER_UPS = 5;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_GLS = 6;</code>
     */
    const SHIPMENT_PROVIDER_GLS = 6;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_FEDEX = 7;</code>
     */
    const SHIPMENT_PROVIDER_FEDEX = 7;
    /**
     * Generated from protobuf enum <code>SHIPMENT_PROVIDER_OTHER = 8;</code>
     */
    const SHIPMENT_PROVIDER_OTHER = 8;

    private static $valueToName = [
        self::SHIPMENT_PROVIDER_UNSPECIFIED => 'SHIPMENT_PROVIDER_UNSPECIFIED',
        self::SHIPMENT_PROVIDER_DEUTSCHE_POST => 'SHIPMENT_PROVIDER_DEUTSCHE_POST',
        self::SHIPMENT_PROVIDER_DHL => 'SHIPMENT_PROVIDER_DHL',
        self::SHIPMENT_PROVIDER_HERMES => 'SHIPMENT_PROVIDER_HERMES',
        self::SHIPMENT_PROVIDER_DPD => 'SHIPMENT_PROVIDER_DPD',
        self::SHIPMENT_PROVIDER_UPS => 'SHIPMENT_PROVIDER_UPS',
        self::SHIPMENT_PROVIDER_GLS => 'SHIPMENT_PROVIDER_GLS',
        self::SHIPMENT_PROVIDER_FEDEX => 'SHIPMENT_PROVIDER_FEDEX',
        self::SHIPMENT_PROVIDER_OTHER => 'SHIPMENT_PROVIDER_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

