<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.v1.ShipmentProvider shipment_provider = 1 [json_name = "shipmentProvider"];</code>
     */
    protected $shipment_provider = 0;
    /**
     * Generated from protobuf field <code>.types.v1.Money price = 2 [json_name = "price"];</code>
     */
    protected $price = null;
    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     */
    protected $tracking_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $shipment_provider
     *     @type \Types\V1\Money $price
     *     @type string $tracking_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.v1.ShipmentProvider shipment_provider = 1 [json_name = "shipmentProvider"];</code>
     * @return int
     */
    public function getShipmentProvider()
    {
        return $this->shipment_provider;
    }

    /**
     * Generated from protobuf field <code>.types.v1.ShipmentProvider shipment_provider = 1 [json_name = "shipmentProvider"];</code>
     * @param int $var
     * @return $this
     */
    public function setShipmentProvider($var)
    {
        GPBUtil::checkEnum($var, \Types\V1\ShipmentProvider::class);
        $this->shipment_provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Money price = 2 [json_name = "price"];</code>
     * @return \Types\V1\Money|null
     */
    public function getPrice()
    {
        return $this->price;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Money price = 2 [json_name = "price"];</code>
     * @param \Types\V1\Money $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Money::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->tracking_number;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_number = $var;

        return $this;
    }

}

