<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/v1/shipping.proto

namespace Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>types.v1.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.v1.Carrier carrier = 1 [json_name = "carrier"];</code>
     */
    protected $carrier = 0;
    /**
     * Generated from protobuf field <code>.google.type.Money shipping_cost = 2 [json_name = "shippingCost"];</code>
     */
    protected $shipping_cost = null;
    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     */
    protected $tracking_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $carrier
     *     @type \Google\Type\Money $shipping_cost
     *     @type string $tracking_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types\V1\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Carrier carrier = 1 [json_name = "carrier"];</code>
     * @return int
     */
    public function getCarrier()
    {
        return $this->carrier;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Carrier carrier = 1 [json_name = "carrier"];</code>
     * @param int $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkEnum($var, \Types\V1\Carrier::class);
        $this->carrier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.type.Money shipping_cost = 2 [json_name = "shippingCost"];</code>
     * @return \Google\Type\Money|null
     */
    public function getShippingCost()
    {
        return $this->shipping_cost;
    }

    public function hasShippingCost()
    {
        return isset($this->shipping_cost);
    }

    public function clearShippingCost()
    {
        unset($this->shipping_cost);
    }

    /**
     * Generated from protobuf field <code>.google.type.Money shipping_cost = 2 [json_name = "shippingCost"];</code>
     * @param \Google\Type\Money $var
     * @return $this
     */
    public function setShippingCost($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Money::class);
        $this->shipping_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->tracking_number;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3 [json_name = "trackingNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_number = $var;

        return $this;
    }

}

