<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configurations_service.proto

namespace GPBMetadata\Configuration\V1;

class ConfigurationsService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x04\x0A-configuration/v1/configurations_service.proto\x12\x10configuration.v12\xDD\x03\x0A\x14ConfigurationService\x12i\x0A\x10GetConfiguration\x12).configuration.v1.GetConfigurationRequest\x1A*.configuration.v1.GetConfigurationResponse\x12r\x0A\x13CreateConfiguration\x12,.configuration.v1.CreateConfigurationRequest\x1A-.configuration.v1.CreateConfigurationResponse\x12r\x0A\x13UpdateConfiguration\x12,.configuration.v1.UpdateConfigurationRequest\x1A-.configuration.v1.UpdateConfigurationResponse\x12r\x0A\x13DeleteConfiguration\x12,.configuration.v1.DeleteConfigurationRequest\x1A-.configuration.v1.DeleteConfigurationResponseBHZFgithub.com/dudochnicht/proto-gen-go/configurationpb/v1;configurationpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

