<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance/v1/finance.proto

namespace GPBMetadata\Finance\V1;

class Finance
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x87\x01\x0A\x18finance/v1/finance.proto\x12\x0Afinance.v1\"\x19\x0A\x07Finance\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02idB<Z:github.com/dudochnicht/proto-gen-go/financepb/v1;financepbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

