<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.BatchGetTransactionsRequest</code>
 */
class BatchGetTransactionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string transaction_ids = 1 [json_name = "transactionIds"];</code>
     */
    private $transaction_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $transaction_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string transaction_ids = 1 [json_name = "transactionIds"];</code>
     * @return RepeatedField<string>
     */
    public function getTransactionIds()
    {
        return $this->transaction_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string transaction_ids = 1 [json_name = "transactionIds"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setTransactionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->transaction_ids = $arr;

        return $this;
    }

}

