<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.GetTransactionResponse</code>
 */
class GetTransactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transaction.v1.Transaction transaction = 1 [json_name = "transaction"];</code>
     */
    protected $transaction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Transaction\V1\Transaction $transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Transaction transaction = 1 [json_name = "transaction"];</code>
     * @return \Transaction\V1\Transaction|null
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Transaction transaction = 1 [json_name = "transaction"];</code>
     * @param \Transaction\V1\Transaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\Transaction::class);
        $this->transaction = $var;

        return $this;
    }

}

