<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.GetTransactionsResponse</code>
 */
class GetTransactionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     */
    private $transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Transaction\V1\Transaction[] $transactions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     * @return RepeatedField<\Transaction\V1\Transaction>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     * @param \Transaction\V1\Transaction[] $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\V1\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

}

