<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>transaction.v1.ItemType</code>
 */
class ItemType
{
    /**
     * Generated from protobuf enum <code>ITEM_TYPE_UNSPECIFIED = 0;</code>
     */
    const ITEM_TYPE_UNSPECIFIED = 0;
    /**
     * Laptop, Tablet, PC, ...
     *
     * Generated from protobuf enum <code>ITEM_TYPE_DEVICE = 1;</code>
     */
    const ITEM_TYPE_DEVICE = 1;
    /**
     * SSD, RAM, Battery, ...
     *
     * Generated from protobuf enum <code>ITEM_TYPE_HARDWARE = 2;</code>
     */
    const ITEM_TYPE_HARDWARE = 2;
    /**
     * Generated from protobuf enum <code>ITEM_TYPE_OTHER = 3;</code>
     */
    const ITEM_TYPE_OTHER = 3;

    private static $valueToName = [
        self::ITEM_TYPE_UNSPECIFIED => 'ITEM_TYPE_UNSPECIFIED',
        self::ITEM_TYPE_DEVICE => 'ITEM_TYPE_DEVICE',
        self::ITEM_TYPE_HARDWARE => 'ITEM_TYPE_HARDWARE',
        self::ITEM_TYPE_OTHER => 'ITEM_TYPE_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

