<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.ListTransactionsResponse</code>
 */
class ListTransactionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     */
    private $transactions;
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     */
    protected $page_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Transaction\V1\Transaction[] $transactions
     *     @type \Types\V1\OffsetPageResult $page_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     * @return RepeatedField<\Transaction\V1\Transaction>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.v1.Transaction transactions = 1 [json_name = "transactions"];</code>
     * @param \Transaction\V1\Transaction[] $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\V1\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @return \Types\V1\OffsetPageResult|null
     */
    public function getPageResult()
    {
        return $this->page_result;
    }

    public function hasPageResult()
    {
        return isset($this->page_result);
    }

    public function clearPageResult()
    {
        unset($this->page_result);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @param \Types\V1\OffsetPageResult $var
     * @return $this
     */
    public function setPageResult($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPageResult::class);
        $this->page_result = $var;

        return $this;
    }

}

