<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.Participant</code>
 */
class Participant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transaction.v1.SalesChannel sales_channel = 1 [json_name = "salesChannel"];</code>
     */
    protected $sales_channel = 0;
    /**
     * Generated from protobuf field <code>string account_name = 2 [json_name = "accountName"];</code>
     */
    protected $account_name = '';
    /**
     * Generated from protobuf field <code>.types.v1.Address address = 3 [json_name = "address"];</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>.transaction.v1.PaymentMethod payment_method = 4 [json_name = "paymentMethod"];</code>
     */
    protected $payment_method = 0;
    /**
     * Generated from protobuf field <code>.google.type.Money amount = 5 [json_name = "amount"];</code>
     */
    protected $amount = null;
    /**
     * Generated from protobuf field <code>.types.v1.ShippingMethod shipping_method = 6 [json_name = "shippingMethod"];</code>
     */
    protected $shipping_method = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    protected $created_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $sales_channel
     *     @type string $account_name
     *     @type \Types\V1\Address $address
     *     @type int $payment_method
     *     @type \Google\Type\Money $amount
     *     @type \Types\V1\ShippingMethod $shipping_method
     *     @type \Google\Protobuf\Timestamp $created_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.SalesChannel sales_channel = 1 [json_name = "salesChannel"];</code>
     * @return int
     */
    public function getSalesChannel()
    {
        return $this->sales_channel;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.SalesChannel sales_channel = 1 [json_name = "salesChannel"];</code>
     * @param int $var
     * @return $this
     */
    public function setSalesChannel($var)
    {
        GPBUtil::checkEnum($var, \Transaction\V1\SalesChannel::class);
        $this->sales_channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_name = 2 [json_name = "accountName"];</code>
     * @return string
     */
    public function getAccountName()
    {
        return $this->account_name;
    }

    /**
     * Generated from protobuf field <code>string account_name = 2 [json_name = "accountName"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountName($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Address address = 3 [json_name = "address"];</code>
     * @return \Types\V1\Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Address address = 3 [json_name = "address"];</code>
     * @param \Types\V1\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.PaymentMethod payment_method = 4 [json_name = "paymentMethod"];</code>
     * @return int
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.PaymentMethod payment_method = 4 [json_name = "paymentMethod"];</code>
     * @param int $var
     * @return $this
     */
    public function setPaymentMethod($var)
    {
        GPBUtil::checkEnum($var, \Transaction\V1\PaymentMethod::class);
        $this->payment_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.type.Money amount = 5 [json_name = "amount"];</code>
     * @return \Google\Type\Money|null
     */
    public function getAmount()
    {
        return $this->amount;
    }

    public function hasAmount()
    {
        return isset($this->amount);
    }

    public function clearAmount()
    {
        unset($this->amount);
    }

    /**
     * Generated from protobuf field <code>.google.type.Money amount = 5 [json_name = "amount"];</code>
     * @param \Google\Type\Money $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Money::class);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.ShippingMethod shipping_method = 6 [json_name = "shippingMethod"];</code>
     * @return \Types\V1\ShippingMethod|null
     */
    public function getShippingMethod()
    {
        return $this->shipping_method;
    }

    public function hasShippingMethod()
    {
        return isset($this->shipping_method);
    }

    public function clearShippingMethod()
    {
        unset($this->shipping_method);
    }

    /**
     * Generated from protobuf field <code>.types.v1.ShippingMethod shipping_method = 6 [json_name = "shippingMethod"];</code>
     * @param \Types\V1\ShippingMethod $var
     * @return $this
     */
    public function setShippingMethod($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\ShippingMethod::class);
        $this->shipping_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

}

