<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>transaction.v1.PaymentMethod</code>
 */
class PaymentMethod
{
    /**
     * Generated from protobuf enum <code>PAYMENT_METHOD_UNSPECIFIED = 0;</code>
     */
    const PAYMENT_METHOD_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PAYMENT_METHOD_PAYPAL = 1;</code>
     */
    const PAYMENT_METHOD_PAYPAL = 1;
    /**
     * Generated from protobuf enum <code>PAYMENT_METHOD_CASH = 2;</code>
     */
    const PAYMENT_METHOD_CASH = 2;
    /**
     * Generated from protobuf enum <code>PAYMENT_METHOD_BANK_TRANSFER = 3;</code>
     */
    const PAYMENT_METHOD_BANK_TRANSFER = 3;

    private static $valueToName = [
        self::PAYMENT_METHOD_UNSPECIFIED => 'PAYMENT_METHOD_UNSPECIFIED',
        self::PAYMENT_METHOD_PAYPAL => 'PAYMENT_METHOD_PAYPAL',
        self::PAYMENT_METHOD_CASH => 'PAYMENT_METHOD_CASH',
        self::PAYMENT_METHOD_BANK_TRANSFER => 'PAYMENT_METHOD_BANK_TRANSFER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

