<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>transaction.v1.Platform</code>
 */
class Platform
{
    /**
     * Generated from protobuf enum <code>PLATFORM_UNSPECIFIED = 0;</code>
     */
    const PLATFORM_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PLATFORM_EBAY = 1;</code>
     */
    const PLATFORM_EBAY = 1;
    /**
     * Generated from protobuf enum <code>PLATFORM_KLEINANZEIGEN = 2;</code>
     */
    const PLATFORM_KLEINANZEIGEN = 2;
    /**
     * Generated from protobuf enum <code>PLATFORM_AMAZON = 3;</code>
     */
    const PLATFORM_AMAZON = 3;
    /**
     * Generated from protobuf enum <code>PLATFORM_OTHER = 4;</code>
     */
    const PLATFORM_OTHER = 4;

    private static $valueToName = [
        self::PLATFORM_UNSPECIFIED => 'PLATFORM_UNSPECIFIED',
        self::PLATFORM_EBAY => 'PLATFORM_EBAY',
        self::PLATFORM_KLEINANZEIGEN => 'PLATFORM_KLEINANZEIGEN',
        self::PLATFORM_AMAZON => 'PLATFORM_AMAZON',
        self::PLATFORM_OTHER => 'PLATFORM_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

