<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>transaction.v1.SalesChannel</code>
 */
class SalesChannel
{
    /**
     * Generated from protobuf enum <code>SALES_CHANNEL_UNSPECIFIED = 0;</code>
     */
    const SALES_CHANNEL_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>SALES_CHANNEL_EBAY = 1;</code>
     */
    const SALES_CHANNEL_EBAY = 1;
    /**
     * Generated from protobuf enum <code>SALES_CHANNEL_KLEINANZEIGEN = 2;</code>
     */
    const SALES_CHANNEL_KLEINANZEIGEN = 2;
    /**
     * Generated from protobuf enum <code>SALES_CHANNEL_AMAZON = 3;</code>
     */
    const SALES_CHANNEL_AMAZON = 3;
    /**
     * Generated from protobuf enum <code>SALES_CHANNEL_OTHER = 4;</code>
     */
    const SALES_CHANNEL_OTHER = 4;

    private static $valueToName = [
        self::SALES_CHANNEL_UNSPECIFIED => 'SALES_CHANNEL_UNSPECIFIED',
        self::SALES_CHANNEL_EBAY => 'SALES_CHANNEL_EBAY',
        self::SALES_CHANNEL_KLEINANZEIGEN => 'SALES_CHANNEL_KLEINANZEIGEN',
        self::SALES_CHANNEL_AMAZON => 'SALES_CHANNEL_AMAZON',
        self::SALES_CHANNEL_OTHER => 'SALES_CHANNEL_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

