<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>transaction.v1.TransactionType</code>
 */
class TransactionType
{
    /**
     * Generated from protobuf enum <code>TRANSACTION_TYPE_UNSPECIFIED = 0;</code>
     */
    const TRANSACTION_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TRANSACTION_TYPE_PURCHASE = 1;</code>
     */
    const TRANSACTION_TYPE_PURCHASE = 1;
    /**
     * Generated from protobuf enum <code>TRANSACTION_TYPE_SALE = 2;</code>
     */
    const TRANSACTION_TYPE_SALE = 2;

    private static $valueToName = [
        self::TRANSACTION_TYPE_UNSPECIFIED => 'TRANSACTION_TYPE_UNSPECIFIED',
        self::TRANSACTION_TYPE_PURCHASE => 'TRANSACTION_TYPE_PURCHASE',
        self::TRANSACTION_TYPE_SALE => 'TRANSACTION_TYPE_SALE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

