<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 2 [json_name = "transactionFrom"];</code>
     */
    protected $transaction_from = null;
    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 3 [json_name = "transactionTo"];</code>
     */
    protected $transaction_to = null;
    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     */
    protected $item_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Transaction\V1\TransactionTransfer $transaction_from
     *     @type \Transaction\V1\TransactionTransfer $transaction_to
     *     @type int $item_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 2 [json_name = "transactionFrom"];</code>
     * @return \Transaction\V1\TransactionTransfer|null
     */
    public function getTransactionFrom()
    {
        return $this->transaction_from;
    }

    public function hasTransactionFrom()
    {
        return isset($this->transaction_from);
    }

    public function clearTransactionFrom()
    {
        unset($this->transaction_from);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 2 [json_name = "transactionFrom"];</code>
     * @param \Transaction\V1\TransactionTransfer $var
     * @return $this
     */
    public function setTransactionFrom($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\TransactionTransfer::class);
        $this->transaction_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 3 [json_name = "transactionTo"];</code>
     * @return \Transaction\V1\TransactionTransfer|null
     */
    public function getTransactionTo()
    {
        return $this->transaction_to;
    }

    public function hasTransactionTo()
    {
        return isset($this->transaction_to);
    }

    public function clearTransactionTo()
    {
        unset($this->transaction_to);
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 3 [json_name = "transactionTo"];</code>
     * @param \Transaction\V1\TransactionTransfer $var
     * @return $this
     */
    public function setTransactionTo($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\TransactionTransfer::class);
        $this->transaction_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     * @return int
     */
    public function getItemType()
    {
        return $this->item_type;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     * @param int $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkEnum($var, \Transaction\V1\ItemType::class);
        $this->item_type = $var;

        return $this;
    }

}

