<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.transaction.v1.Participant seller = 2 [json_name = "seller"];</code>
     */
    protected $seller = null;
    /**
     * Generated from protobuf field <code>optional .transaction.v1.Participant buyer = 3 [json_name = "buyer"];</code>
     */
    protected $buyer = null;
    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     */
    protected $item_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Transaction\V1\Participant $seller
     *     @type \Transaction\V1\Participant $buyer
     *     @type int $item_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Participant seller = 2 [json_name = "seller"];</code>
     * @return \Transaction\V1\Participant|null
     */
    public function getSeller()
    {
        return $this->seller;
    }

    public function hasSeller()
    {
        return isset($this->seller);
    }

    public function clearSeller()
    {
        unset($this->seller);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Participant seller = 2 [json_name = "seller"];</code>
     * @param \Transaction\V1\Participant $var
     * @return $this
     */
    public function setSeller($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\Participant::class);
        $this->seller = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.Participant buyer = 3 [json_name = "buyer"];</code>
     * @return \Transaction\V1\Participant|null
     */
    public function getBuyer()
    {
        return $this->buyer;
    }

    public function hasBuyer()
    {
        return isset($this->buyer);
    }

    public function clearBuyer()
    {
        unset($this->buyer);
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.Participant buyer = 3 [json_name = "buyer"];</code>
     * @param \Transaction\V1\Participant $var
     * @return $this
     */
    public function setBuyer($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\Participant::class);
        $this->buyer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     * @return int
     */
    public function getItemType()
    {
        return $this->item_type;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.ItemType item_type = 4 [json_name = "itemType"];</code>
     * @param int $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkEnum($var, \Transaction\V1\ItemType::class);
        $this->item_type = $var;

        return $this;
    }

}

