<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.UpdateTransactionRequest</code>
 */
class UpdateTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 1 [json_name = "transactionFrom"];</code>
     */
    protected $transaction_from = null;
    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 2 [json_name = "transactionTo"];</code>
     */
    protected $transaction_to = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Transaction\V1\TransactionTransfer $transaction_from
     *     @type \Transaction\V1\TransactionTransfer $transaction_to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 1 [json_name = "transactionFrom"];</code>
     * @return \Transaction\V1\TransactionTransfer|null
     */
    public function getTransactionFrom()
    {
        return $this->transaction_from;
    }

    public function hasTransactionFrom()
    {
        return isset($this->transaction_from);
    }

    public function clearTransactionFrom()
    {
        unset($this->transaction_from);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.TransactionTransfer transaction_from = 1 [json_name = "transactionFrom"];</code>
     * @param \Transaction\V1\TransactionTransfer $var
     * @return $this
     */
    public function setTransactionFrom($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\TransactionTransfer::class);
        $this->transaction_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 2 [json_name = "transactionTo"];</code>
     * @return \Transaction\V1\TransactionTransfer|null
     */
    public function getTransactionTo()
    {
        return $this->transaction_to;
    }

    public function hasTransactionTo()
    {
        return isset($this->transaction_to);
    }

    public function clearTransactionTo()
    {
        unset($this->transaction_to);
    }

    /**
     * Generated from protobuf field <code>optional .transaction.v1.TransactionTransfer transaction_to = 2 [json_name = "transactionTo"];</code>
     * @param \Transaction\V1\TransactionTransfer $var
     * @return $this
     */
    public function setTransactionTo($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\TransactionTransfer::class);
        $this->transaction_to = $var;

        return $this;
    }

}

