<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction.proto

namespace Transaction\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.v1.UpdateBuyerTransactionRequest</code>
 */
class UpdateBuyerTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transaction_id = 1 [json_name = "transactionId"];</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>.transaction.v1.Participant buyer = 2 [json_name = "buyer"];</code>
     */
    protected $buyer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_id
     *     @type \Transaction\V1\Participant $buyer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 1 [json_name = "transactionId"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 1 [json_name = "transactionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Participant buyer = 2 [json_name = "buyer"];</code>
     * @return \Transaction\V1\Participant|null
     */
    public function getBuyer()
    {
        return $this->buyer;
    }

    public function hasBuyer()
    {
        return isset($this->buyer);
    }

    public function clearBuyer()
    {
        unset($this->buyer);
    }

    /**
     * Generated from protobuf field <code>.transaction.v1.Participant buyer = 2 [json_name = "buyer"];</code>
     * @param \Transaction\V1\Participant $var
     * @return $this
     */
    public function setBuyer($var)
    {
        GPBUtil::checkMessage($var, \Transaction\V1\Participant::class);
        $this->buyer = $var;

        return $this;
    }

}

