<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.AllowedSetting</code>
 */
class AllowedSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 slot_counts = 1 [json_name = "slotCounts"];</code>
     */
    protected $slot_counts = 0;
    /**
     * Generated from protobuf field <code>bool is_soldered = 2 [json_name = "isSoldered"];</code>
     */
    protected $is_soldered = false;
    /**
     * Generated from protobuf field <code>string support_note = 3 [json_name = "supportNote"];</code>
     */
    protected $support_note = '';
    /**
     * references BrandService.Hardware
     *
     * Generated from protobuf field <code>string hardware_id = 4 [json_name = "hardwareId"];</code>
     */
    protected $hardware_id = '';
    /**
     * references BrandService.Specification
     *
     * Generated from protobuf field <code>repeated string specification_ids = 5 [json_name = "specificationIds"];</code>
     */
    private $specification_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $slot_counts
     *     @type bool $is_soldered
     *     @type string $support_note
     *     @type string $hardware_id
     *           references BrandService.Hardware
     *     @type string[] $specification_ids
     *           references BrandService.Specification
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 slot_counts = 1 [json_name = "slotCounts"];</code>
     * @return int
     */
    public function getSlotCounts()
    {
        return $this->slot_counts;
    }

    /**
     * Generated from protobuf field <code>int32 slot_counts = 1 [json_name = "slotCounts"];</code>
     * @param int $var
     * @return $this
     */
    public function setSlotCounts($var)
    {
        GPBUtil::checkInt32($var);
        $this->slot_counts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_soldered = 2 [json_name = "isSoldered"];</code>
     * @return bool
     */
    public function getIsSoldered()
    {
        return $this->is_soldered;
    }

    /**
     * Generated from protobuf field <code>bool is_soldered = 2 [json_name = "isSoldered"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSoldered($var)
    {
        GPBUtil::checkBool($var);
        $this->is_soldered = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string support_note = 3 [json_name = "supportNote"];</code>
     * @return string
     */
    public function getSupportNote()
    {
        return $this->support_note;
    }

    /**
     * Generated from protobuf field <code>string support_note = 3 [json_name = "supportNote"];</code>
     * @param string $var
     * @return $this
     */
    public function setSupportNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->support_note = $var;

        return $this;
    }

    /**
     * references BrandService.Hardware
     *
     * Generated from protobuf field <code>string hardware_id = 4 [json_name = "hardwareId"];</code>
     * @return string
     */
    public function getHardwareId()
    {
        return $this->hardware_id;
    }

    /**
     * references BrandService.Hardware
     *
     * Generated from protobuf field <code>string hardware_id = 4 [json_name = "hardwareId"];</code>
     * @param string $var
     * @return $this
     */
    public function setHardwareId($var)
    {
        GPBUtil::checkString($var, True);
        $this->hardware_id = $var;

        return $this;
    }

    /**
     * references BrandService.Specification
     *
     * Generated from protobuf field <code>repeated string specification_ids = 5 [json_name = "specificationIds"];</code>
     * @return RepeatedField<string>
     */
    public function getSpecificationIds()
    {
        return $this->specification_ids;
    }

    /**
     * references BrandService.Specification
     *
     * Generated from protobuf field <code>repeated string specification_ids = 5 [json_name = "specificationIds"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setSpecificationIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->specification_ids = $arr;

        return $this;
    }

}

