<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.BatchGetItemsRequest</code>
 */
class BatchGetItemsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string item_ids = 1 [json_name = "itemIds"];</code>
     */
    private $item_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $item_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string item_ids = 1 [json_name = "itemIds"];</code>
     * @return RepeatedField<string>
     */
    public function getItemIds()
    {
        return $this->item_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string item_ids = 1 [json_name = "itemIds"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setItemIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->item_ids = $arr;

        return $this;
    }

}

