<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.BatchGetComponentsResponse</code>
 */
class BatchGetComponentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Component components = 1 [json_name = "components"];</code>
     */
    private $components;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Component[] $components
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Component components = 1 [json_name = "components"];</code>
     * @return RepeatedField<\Catalog\V1\Component>
     */
    public function getComponents()
    {
        return $this->components;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Component components = 1 [json_name = "components"];</code>
     * @param \Catalog\V1\Component[] $var
     * @return $this
     */
    public function setComponents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\Component::class);
        $this->components = $arr;

        return $this;
    }

}

