<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.ConfigurationTemplate</code>
 */
class ConfigurationTemplate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * references BrandService.Model
     *
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     */
    protected $model_id = '';
    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_from = 3 [json_name = "manufacturedFrom"];</code>
     */
    protected $manufactured_from = null;
    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_to = 4 [json_name = "manufacturedTo"];</code>
     */
    protected $manufactured_to = null;
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 5 [json_name = "allowedSettings"];</code>
     */
    private $allowed_settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $model_id
     *           references BrandService.Model
     *     @type \Types\V1\Date $manufactured_from
     *     @type \Types\V1\Date $manufactured_to
     *     @type \Catalog\V1\AllowedSetting[] $allowed_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * references BrandService.Model
     *
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     * @return string
     */
    public function getModelId()
    {
        return $this->model_id;
    }

    /**
     * references BrandService.Model
     *
     * Generated from protobuf field <code>string model_id = 2 [json_name = "modelId"];</code>
     * @param string $var
     * @return $this
     */
    public function setModelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_from = 3 [json_name = "manufacturedFrom"];</code>
     * @return \Types\V1\Date|null
     */
    public function getManufacturedFrom()
    {
        return $this->manufactured_from;
    }

    public function hasManufacturedFrom()
    {
        return isset($this->manufactured_from);
    }

    public function clearManufacturedFrom()
    {
        unset($this->manufactured_from);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_from = 3 [json_name = "manufacturedFrom"];</code>
     * @param \Types\V1\Date $var
     * @return $this
     */
    public function setManufacturedFrom($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Date::class);
        $this->manufactured_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_to = 4 [json_name = "manufacturedTo"];</code>
     * @return \Types\V1\Date|null
     */
    public function getManufacturedTo()
    {
        return $this->manufactured_to;
    }

    public function hasManufacturedTo()
    {
        return isset($this->manufactured_to);
    }

    public function clearManufacturedTo()
    {
        unset($this->manufactured_to);
    }

    /**
     * Generated from protobuf field <code>.types.v1.Date manufactured_to = 4 [json_name = "manufacturedTo"];</code>
     * @param \Types\V1\Date $var
     * @return $this
     */
    public function setManufacturedTo($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\Date::class);
        $this->manufactured_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 5 [json_name = "allowedSettings"];</code>
     * @return RepeatedField<\Catalog\V1\AllowedSetting>
     */
    public function getAllowedSettings()
    {
        return $this->allowed_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 5 [json_name = "allowedSettings"];</code>
     * @param \Catalog\V1\AllowedSetting[] $var
     * @return $this
     */
    public function setAllowedSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\AllowedSetting::class);
        $this->allowed_settings = $arr;

        return $this;
    }

}

