<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.CreateConfigurationTemplateResponse</code>
 */
class CreateConfigurationTemplateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     */
    protected $configuration_template_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configuration_template_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     * @return string
     */
    public function getConfigurationTemplateId()
    {
        return $this->configuration_template_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_template_id = $var;

        return $this;
    }

}

