<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.CreateModelRequest</code>
 */
class CreateModelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string serie_id = 1 [json_name = "serieId"];</code>
     */
    protected $serie_id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serie_id
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string serie_id = 1 [json_name = "serieId"];</code>
     * @return string
     */
    public function getSerieId()
    {
        return $this->serie_id;
    }

    /**
     * Generated from protobuf field <code>string serie_id = 1 [json_name = "serieId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerieId($var)
    {
        GPBUtil::checkString($var, True);
        $this->serie_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

