<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.CreateFamilyRequest</code>
 */
class CreateFamilyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     */
    protected $component_id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string note = 3 [json_name = "note"];</code>
     */
    protected $note = '';
    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     */
    protected $sequence = 0;
    /**
     * Generated from protobuf field <code>string category = 5 [json_name = "category"];</code>
     */
    protected $category = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $component_id
     *     @type string $name
     *     @type string $note
     *     @type int $sequence
     *     @type string $category
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @return string
     */
    public function getComponentId()
    {
        return $this->component_id;
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @param string $var
     * @return $this
     */
    public function setComponentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 3 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 3 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt32($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 5 [json_name = "category"];</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 5 [json_name = "category"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

}

