<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetComponentResponse</code>
 */
class GetComponentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Component component = 1 [json_name = "component"];</code>
     */
    protected $component = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Component $component
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Component component = 1 [json_name = "component"];</code>
     * @return \Catalog\V1\Component|null
     */
    public function getComponent()
    {
        return $this->component;
    }

    public function hasComponent()
    {
        return isset($this->component);
    }

    public function clearComponent()
    {
        unset($this->component);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Component component = 1 [json_name = "component"];</code>
     * @param \Catalog\V1\Component $var
     * @return $this
     */
    public function setComponent($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Component::class);
        $this->component = $var;

        return $this;
    }

}

