<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetDeviceNameResponse</code>
 */
class GetDeviceNameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * DeviceName (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>string device_name = 1 [json_name = "deviceName"];</code>
     */
    protected $device_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_name
     *           DeviceName (BrandName + SerieName + ModelName)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * DeviceName (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>string device_name = 1 [json_name = "deviceName"];</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * DeviceName (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>string device_name = 1 [json_name = "deviceName"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

}

