<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetDeviceNamesResponse</code>
 */
class GetDeviceNamesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Key = ModelID, Value = DeviceNames (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 1 [json_name = "deviceNames"];</code>
     */
    private $device_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $device_names
     *           Key = ModelID, Value = DeviceNames (BrandName + SerieName + ModelName)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Key = ModelID, Value = DeviceNames (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 1 [json_name = "deviceNames"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getDeviceNames()
    {
        return $this->device_names;
    }

    /**
     * Key = ModelID, Value = DeviceNames (BrandName + SerieName + ModelName)
     *
     * Generated from protobuf field <code>map<string, .catalog.v1.DeviceName> device_names = 1 [json_name = "deviceNames"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setDeviceNames($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\DeviceName::class);
        $this->device_names = $arr;

        return $this;
    }

}

