<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetFamilyResponse</code>
 */
class GetFamilyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Family family = 1 [json_name = "family"];</code>
     */
    protected $family = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Family $family
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Family family = 1 [json_name = "family"];</code>
     * @return \Catalog\V1\Family|null
     */
    public function getFamily()
    {
        return $this->family;
    }

    public function hasFamily()
    {
        return isset($this->family);
    }

    public function clearFamily()
    {
        unset($this->family);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Family family = 1 [json_name = "family"];</code>
     * @param \Catalog\V1\Family $var
     * @return $this
     */
    public function setFamily($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Family::class);
        $this->family = $var;

        return $this;
    }

}

