<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetFamiliesResponse</code>
 */
class GetFamiliesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Family families = 1 [json_name = "families"];</code>
     */
    private $families;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Family[] $families
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Family families = 1 [json_name = "families"];</code>
     * @return RepeatedField<\Catalog\V1\Family>
     */
    public function getFamilies()
    {
        return $this->families;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Family families = 1 [json_name = "families"];</code>
     * @param \Catalog\V1\Family[] $var
     * @return $this
     */
    public function setFamilies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\Family::class);
        $this->families = $arr;

        return $this;
    }

}

