<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetFullModelNameResponse</code>
 */
class GetFullModelNameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string full_model_name = 1 [json_name = "fullModelName"];</code>
     */
    protected $full_model_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $full_model_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string full_model_name = 1 [json_name = "fullModelName"];</code>
     * @return string
     */
    public function getFullModelName()
    {
        return $this->full_model_name;
    }

    /**
     * Generated from protobuf field <code>string full_model_name = 1 [json_name = "fullModelName"];</code>
     * @param string $var
     * @return $this
     */
    public function setFullModelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_model_name = $var;

        return $this;
    }

}

