<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetFullModelNamesResponse</code>
 */
class GetFullModelNamesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.FullModelName full_model_names = 1 [json_name = "fullModelNames"];</code>
     */
    private $full_model_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\FullModelName[] $full_model_names
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.FullModelName full_model_names = 1 [json_name = "fullModelNames"];</code>
     * @return RepeatedField<\Catalog\V1\FullModelName>
     */
    public function getFullModelNames()
    {
        return $this->full_model_names;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.FullModelName full_model_names = 1 [json_name = "fullModelNames"];</code>
     * @param \Catalog\V1\FullModelName[] $var
     * @return $this
     */
    public function setFullModelNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\FullModelName::class);
        $this->full_model_names = $arr;

        return $this;
    }

}

