<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetFullModelNamesRequest</code>
 */
class GetFullModelNamesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string model_ids = 1 [json_name = "modelIds"];</code>
     */
    private $model_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $model_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string model_ids = 1 [json_name = "modelIds"];</code>
     * @return RepeatedField<string>
     */
    public function getModelIds()
    {
        return $this->model_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string model_ids = 1 [json_name = "modelIds"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setModelIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->model_ids = $arr;

        return $this;
    }

}

