<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetItemResponse</code>
 */
class GetItemResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Item item = 1 [json_name = "item"];</code>
     */
    protected $item = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Item $item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Item item = 1 [json_name = "item"];</code>
     * @return \Catalog\V1\Item|null
     */
    public function getItem()
    {
        return $this->item;
    }

    public function hasItem()
    {
        return isset($this->item);
    }

    public function clearItem()
    {
        unset($this->item);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Item item = 1 [json_name = "item"];</code>
     * @param \Catalog\V1\Item $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Item::class);
        $this->item = $var;

        return $this;
    }

}

