<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetModelResponse</code>
 */
class GetModelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Model model = 1 [json_name = "model"];</code>
     */
    protected $model = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Model $model
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Model model = 1 [json_name = "model"];</code>
     * @return \Catalog\V1\Model|null
     */
    public function getModel()
    {
        return $this->model;
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Model model = 1 [json_name = "model"];</code>
     * @param \Catalog\V1\Model $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Model::class);
        $this->model = $var;

        return $this;
    }

}

