<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.GetSerieResponse</code>
 */
class GetSerieResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.catalog.v1.Serie serie = 1 [json_name = "serie"];</code>
     */
    protected $serie = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\Serie $serie
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Serie serie = 1 [json_name = "serie"];</code>
     * @return \Catalog\V1\Serie|null
     */
    public function getSerie()
    {
        return $this->serie;
    }

    public function hasSerie()
    {
        return isset($this->serie);
    }

    public function clearSerie()
    {
        unset($this->serie);
    }

    /**
     * Generated from protobuf field <code>.catalog.v1.Serie serie = 1 [json_name = "serie"];</code>
     * @param \Catalog\V1\Serie $var
     * @return $this
     */
    public function setSerie($var)
    {
        GPBUtil::checkMessage($var, \Catalog\V1\Serie::class);
        $this->serie = $var;

        return $this;
    }

}

