<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string family_id = 2 [json_name = "familyId"];</code>
     */
    protected $family_id = '';
    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     */
    protected $note = null;
    /**
     * Generated from protobuf field <code>int32 sequence = 5 [json_name = "sequence"];</code>
     */
    protected $sequence = 0;
    /**
     * Generated from protobuf field <code>int32 quantity = 6 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>optional string category = 7 [json_name = "category"];</code>
     */
    protected $category = null;
    /**
     * Generated from protobuf field <code>optional int32 in_uses_count = 8 [json_name = "inUsesCount"];</code>
     */
    protected $in_uses_count = null;
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Property properties = 9 [json_name = "properties"];</code>
     */
    private $properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $family_id
     *     @type string $name
     *     @type string $note
     *     @type int $sequence
     *     @type int $quantity
     *     @type string $category
     *     @type int $in_uses_count
     *     @type \Catalog\V1\Property[] $properties
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string family_id = 2 [json_name = "familyId"];</code>
     * @return string
     */
    public function getFamilyId()
    {
        return $this->family_id;
    }

    /**
     * Generated from protobuf field <code>string family_id = 2 [json_name = "familyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFamilyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->family_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return isset($this->note) ? $this->note : '';
    }

    public function hasNote()
    {
        return isset($this->note);
    }

    public function clearNote()
    {
        unset($this->note);
    }

    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 5 [json_name = "sequence"];</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 5 [json_name = "sequence"];</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt32($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 6 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 6 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string category = 7 [json_name = "category"];</code>
     * @return string
     */
    public function getCategory()
    {
        return isset($this->category) ? $this->category : '';
    }

    public function hasCategory()
    {
        return isset($this->category);
    }

    public function clearCategory()
    {
        unset($this->category);
    }

    /**
     * Generated from protobuf field <code>optional string category = 7 [json_name = "category"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 in_uses_count = 8 [json_name = "inUsesCount"];</code>
     * @return int
     */
    public function getInUsesCount()
    {
        return isset($this->in_uses_count) ? $this->in_uses_count : 0;
    }

    public function hasInUsesCount()
    {
        return isset($this->in_uses_count);
    }

    public function clearInUsesCount()
    {
        unset($this->in_uses_count);
    }

    /**
     * Generated from protobuf field <code>optional int32 in_uses_count = 8 [json_name = "inUsesCount"];</code>
     * @param int $var
     * @return $this
     */
    public function setInUsesCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->in_uses_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Property properties = 9 [json_name = "properties"];</code>
     * @return RepeatedField<\Catalog\V1\Property>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.Property properties = 9 [json_name = "properties"];</code>
     * @param \Catalog\V1\Property[] $var
     * @return $this
     */
    public function setProperties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\Property::class);
        $this->properties = $arr;

        return $this;
    }

}

