<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.ListItemsByFamilyRequest</code>
 */
class ListItemsByFamilyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     */
    protected $family_id = '';
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $family_id
     *     @type \Types\V1\OffsetPage $page
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     * @return string
     */
    public function getFamilyId()
    {
        return $this->family_id;
    }

    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFamilyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->family_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     * @return \Types\V1\OffsetPage|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPage page = 2 [json_name = "page"];</code>
     * @param \Types\V1\OffsetPage $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPage::class);
        $this->page = $var;

        return $this;
    }

}

