<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.ListConfigurationTemplatesResponse</code>
 */
class ListConfigurationTemplatesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.ConfigurationTemplate configuration_templates = 1 [json_name = "configurationTemplates"];</code>
     */
    private $configuration_templates;
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     */
    protected $page_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Catalog\V1\ConfigurationTemplate[] $configuration_templates
     *     @type \Types\V1\OffsetPageResult $page_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.ConfigurationTemplate configuration_templates = 1 [json_name = "configurationTemplates"];</code>
     * @return RepeatedField<\Catalog\V1\ConfigurationTemplate>
     */
    public function getConfigurationTemplates()
    {
        return $this->configuration_templates;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.ConfigurationTemplate configuration_templates = 1 [json_name = "configurationTemplates"];</code>
     * @param \Catalog\V1\ConfigurationTemplate[] $var
     * @return $this
     */
    public function setConfigurationTemplates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\ConfigurationTemplate::class);
        $this->configuration_templates = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @return \Types\V1\OffsetPageResult|null
     */
    public function getPageResult()
    {
        return $this->page_result;
    }

    public function hasPageResult()
    {
        return isset($this->page_result);
    }

    public function clearPageResult()
    {
        unset($this->page_result);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @param \Types\V1\OffsetPageResult $var
     * @return $this
     */
    public function setPageResult($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPageResult::class);
        $this->page_result = $var;

        return $this;
    }

}

