<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.Model</code>
 */
class Model extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string serie_id = 3 [json_name = "serieId"];</code>
     */
    protected $serie_id = '';
    /**
     * Generated from protobuf field <code>optional int32 devices_count = 4 [json_name = "devicesCount"];</code>
     */
    protected $devices_count = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $serie_id
     *     @type int $devices_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serie_id = 3 [json_name = "serieId"];</code>
     * @return string
     */
    public function getSerieId()
    {
        return $this->serie_id;
    }

    /**
     * Generated from protobuf field <code>string serie_id = 3 [json_name = "serieId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerieId($var)
    {
        GPBUtil::checkString($var, True);
        $this->serie_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 devices_count = 4 [json_name = "devicesCount"];</code>
     * @return int
     */
    public function getDevicesCount()
    {
        return isset($this->devices_count) ? $this->devices_count : 0;
    }

    public function hasDevicesCount()
    {
        return isset($this->devices_count);
    }

    public function clearDevicesCount()
    {
        unset($this->devices_count);
    }

    /**
     * Generated from protobuf field <code>optional int32 devices_count = 4 [json_name = "devicesCount"];</code>
     * @param int $var
     * @return $this
     */
    public function setDevicesCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->devices_count = $var;

        return $this;
    }

}

