<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.SearchItemsRequest</code>
 */
class SearchItemsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string family_ids = 1 [json_name = "familyIds"];</code>
     */
    private $family_ids;
    /**
     * Generated from protobuf field <code>string query = 2 [json_name = "query"];</code>
     */
    protected $query = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $family_ids
     *     @type string $query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string family_ids = 1 [json_name = "familyIds"];</code>
     * @return RepeatedField<string>
     */
    public function getFamilyIds()
    {
        return $this->family_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string family_ids = 1 [json_name = "familyIds"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setFamilyIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->family_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query = 2 [json_name = "query"];</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>string query = 2 [json_name = "query"];</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;

        return $this;
    }

}

