<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.Serie</code>
 */
class Serie extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string brand_id = 3 [json_name = "brandId"];</code>
     */
    protected $brand_id = '';
    /**
     * Generated from protobuf field <code>optional int32 models_count = 4 [json_name = "modelsCount"];</code>
     */
    protected $models_count = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $brand_id
     *     @type int $models_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brand_id = 3 [json_name = "brandId"];</code>
     * @return string
     */
    public function getBrandId()
    {
        return $this->brand_id;
    }

    /**
     * Generated from protobuf field <code>string brand_id = 3 [json_name = "brandId"];</code>
     * @param string $var
     * @return $this
     */
    public function setBrandId($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 models_count = 4 [json_name = "modelsCount"];</code>
     * @return int
     */
    public function getModelsCount()
    {
        return isset($this->models_count) ? $this->models_count : 0;
    }

    public function hasModelsCount()
    {
        return isset($this->models_count);
    }

    public function clearModelsCount()
    {
        unset($this->models_count);
    }

    /**
     * Generated from protobuf field <code>optional int32 models_count = 4 [json_name = "modelsCount"];</code>
     * @param int $var
     * @return $this
     */
    public function setModelsCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->models_count = $var;

        return $this;
    }

}

