<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.UpdateComponentRequest</code>
 */
class UpdateComponentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     */
    protected $component_id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 sequence = 3 [json_name = "sequence"];</code>
     */
    protected $sequence = 0;
    /**
     * Generated from protobuf field <code>string icon = 4 [json_name = "icon"];</code>
     */
    protected $icon = '';
    /**
     * Generated from protobuf field <code>bool soldered = 5 [json_name = "soldered"];</code>
     */
    protected $soldered = false;
    /**
     * Generated from protobuf field <code>bool visible = 6 [json_name = "visible"];</code>
     */
    protected $visible = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $component_id
     *     @type string $name
     *     @type int $sequence
     *     @type string $icon
     *     @type bool $soldered
     *     @type bool $visible
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @return string
     */
    public function getComponentId()
    {
        return $this->component_id;
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @param string $var
     * @return $this
     */
    public function setComponentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 3 [json_name = "sequence"];</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 3 [json_name = "sequence"];</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt32($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 4 [json_name = "icon"];</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 4 [json_name = "icon"];</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool soldered = 5 [json_name = "soldered"];</code>
     * @return bool
     */
    public function getSoldered()
    {
        return $this->soldered;
    }

    /**
     * Generated from protobuf field <code>bool soldered = 5 [json_name = "soldered"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSoldered($var)
    {
        GPBUtil::checkBool($var);
        $this->soldered = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool visible = 6 [json_name = "visible"];</code>
     * @return bool
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Generated from protobuf field <code>bool visible = 6 [json_name = "visible"];</code>
     * @param bool $var
     * @return $this
     */
    public function setVisible($var)
    {
        GPBUtil::checkBool($var);
        $this->visible = $var;

        return $this;
    }

}

