<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.UpdateConfigurationTemplateRequest</code>
 */
class UpdateConfigurationTemplateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     */
    protected $configuration_template_id = '';
    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 2 [json_name = "allowedSettings"];</code>
     */
    private $allowed_settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configuration_template_id
     *     @type \Catalog\V1\AllowedSetting[] $allowed_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     * @return string
     */
    public function getConfigurationTemplateId()
    {
        return $this->configuration_template_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_template_id = 1 [json_name = "configurationTemplateId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_template_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 2 [json_name = "allowedSettings"];</code>
     * @return RepeatedField<\Catalog\V1\AllowedSetting>
     */
    public function getAllowedSettings()
    {
        return $this->allowed_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .catalog.v1.AllowedSetting allowed_settings = 2 [json_name = "allowedSettings"];</code>
     * @param \Catalog\V1\AllowedSetting[] $var
     * @return $this
     */
    public function setAllowedSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\V1\AllowedSetting::class);
        $this->allowed_settings = $arr;

        return $this;
    }

}

