<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware.proto

namespace Catalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>catalog.v1.UpdateFamilyRequest</code>
 */
class UpdateFamilyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     */
    protected $family_id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string note = 3 [json_name = "note"];</code>
     */
    protected $note = null;
    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     */
    protected $sequence = 0;
    /**
     * Generated from protobuf field <code>optional string category = 5 [json_name = "category"];</code>
     */
    protected $category = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $family_id
     *     @type string $name
     *     @type string $note
     *     @type int $sequence
     *     @type string $category
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     * @return string
     */
    public function getFamilyId()
    {
        return $this->family_id;
    }

    /**
     * Generated from protobuf field <code>string family_id = 1 [json_name = "familyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFamilyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->family_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string note = 3 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return isset($this->note) ? $this->note : '';
    }

    public function hasNote()
    {
        return isset($this->note);
    }

    public function clearNote()
    {
        unset($this->note);
    }

    /**
     * Generated from protobuf field <code>optional string note = 3 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>int32 sequence = 4 [json_name = "sequence"];</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt32($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string category = 5 [json_name = "category"];</code>
     * @return string
     */
    public function getCategory()
    {
        return isset($this->category) ? $this->category : '';
    }

    public function hasCategory()
    {
        return isset($this->category);
    }

    public function clearCategory()
    {
        unset($this->category);
    }

    /**
     * Generated from protobuf field <code>optional string category = 5 [json_name = "category"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

}

