<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction_service.proto

namespace GPBMetadata\Transaction\V1;

class TransactionService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x06\x0A(transaction/v1/transaction_service.proto\x12\x0Etransaction.v12\xFE\x04\x0A\x12TransactionService\x12e\x0A\x10ListTransactions\x12'.transaction.v1.ListTransactionsRequest\x1A(.transaction.v1.ListTransactionsResponse\x12_\x0A\x0EGetTransaction\x12%.transaction.v1.GetTransactionRequest\x1A&.transaction.v1.GetTransactionResponse\x12b\x0A\x0FGetTransactions\x12&.transaction.v1.GetTransactionsRequest\x1A'.transaction.v1.GetTransactionsResponse\x12h\x0A\x11CreateTransaction\x12(.transaction.v1.CreateTransactionRequest\x1A).transaction.v1.CreateTransactionResponse\x12h\x0A\x11UpdateTransaction\x12(.transaction.v1.UpdateTransactionRequest\x1A).transaction.v1.UpdateTransactionResponse\x12h\x0A\x11DeleteTransaction\x12(.transaction.v1.DeleteTransactionRequest\x1A).transaction.v1.DeleteTransactionResponseBDZBgithub.com/dudochnicht/proto-gen-go/transactionpb/v1;transactionpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

