<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/v1/transaction_service.proto

namespace GPBMetadata\Transaction\V1;

class TransactionService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transaction\V1\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBC\x06\x0A(transaction/v1/transaction_service.proto\x12\x0Etransaction.v12\xB1\x05\x0A\x12TransactionService\x12_\x0A\x0EGetTransaction\x12%.transaction.v1.GetTransactionRequest\x1A&.transaction.v1.GetTransactionResponse\x12q\x0A\x14BatchGetTransactions\x12+.transaction.v1.BatchGetTransactionsRequest\x1A,.transaction.v1.BatchGetTransactionsResponse\x12h\x0A\x11CreateTransaction\x12(.transaction.v1.CreateTransactionRequest\x1A).transaction.v1.CreateTransactionResponse\x12z\x0A\x17UpdateSellerTransaction\x12..transaction.v1.UpdateSellerTransactionRequest\x1A/.transaction.v1.UpdateSellerTransactionResponse\x12w\x0A\x16UpdateBuyerTransaction\x12-.transaction.v1.UpdateBuyerTransactionRequest\x1A..transaction.v1.UpdateBuyerTransactionResponse\x12h\x0A\x11DeleteTransaction\x12(.transaction.v1.DeleteTransactionRequest\x1A).transaction.v1.DeleteTransactionResponseBDZBgithub.com/dudochnicht/proto-gen-go/transactionpb/v1;transactionpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

