<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/configuration_template_service.proto

namespace GPBMetadata\Catalog\V1;

class ConfigurationTemplateService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Catalog\V1\ConfigurationTemplate::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAB\x06\x0A/catalog/v1/configuration_template_service.proto\x12\x0Acatalog.v12\xA5\x05\x0A\x1CConfigurationTemplateService\x12\x8D\x01\x0A FindConfigurationTemplateByModel\x123.catalog.v1.FindConfigurationTemplateByModelRequest\x1A4.catalog.v1.FindConfigurationTemplateByModelResponse\x12u\x0A\x18GetConfigurationTemplate\x12+.catalog.v1.GetConfigurationTemplateRequest\x1A,.catalog.v1.GetConfigurationTemplateResponse\x12~\x0A\x1BCreateConfigurationTemplate\x12..catalog.v1.CreateConfigurationTemplateRequest\x1A/.catalog.v1.CreateConfigurationTemplateResponse\x12~\x0A\x1BUpdateConfigurationTemplate\x12..catalog.v1.UpdateConfigurationTemplateRequest\x1A/.catalog.v1.UpdateConfigurationTemplateResponse\x12~\x0A\x1BDeleteConfigurationTemplate\x12..catalog.v1.DeleteConfigurationTemplateRequest\x1A/.catalog.v1.DeleteConfigurationTemplateResponseB<Z:github.com/dudochnicht/proto-gen-go/catalogpb/v1;catalogpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

