<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/hardware_service.proto

namespace GPBMetadata\Catalog\V1;

class HardwareService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Catalog\V1\Hardware::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x0A\x0A!catalog/v1/hardware_service.proto\x12\x0Acatalog.v12\xDC\x09\x0A\x0FHardwareService\x12W\x0A\x0EListComponents\x12!.catalog.v1.ListComponentsRequest\x1A\".catalog.v1.ListComponentsResponse\x12Q\x0A\x0CGetComponent\x12\x1F.catalog.v1.GetComponentRequest\x1A .catalog.v1.GetComponentResponse\x12Z\x0A\x0FCreateComponent\x12\".catalog.v1.CreateComponentRequest\x1A#.catalog.v1.CreateComponentResponse\x12Z\x0A\x0FUpdateComponent\x12\".catalog.v1.UpdateComponentRequest\x1A#.catalog.v1.UpdateComponentResponse\x12Z\x0A\x0FDeleteComponent\x12\".catalog.v1.DeleteComponentRequest\x1A#.catalog.v1.DeleteComponentResponse\x12Q\x0A\x0CListFamilies\x12\x1F.catalog.v1.ListFamiliesRequest\x1A .catalog.v1.ListFamiliesResponse\x12H\x0A\x09GetFamily\x12\x1C.catalog.v1.GetFamilyRequest\x1A\x1D.catalog.v1.GetFamilyResponse\x12Q\x0A\x0CCreateFamily\x12\x1F.catalog.v1.CreateFamilyRequest\x1A .catalog.v1.CreateFamilyResponse\x12Q\x0A\x0CUpdateFamily\x12\x1F.catalog.v1.UpdateFamilyRequest\x1A .catalog.v1.UpdateFamilyResponse\x12Q\x0A\x0CDeleteFamily\x12\x1F.catalog.v1.DeleteFamilyRequest\x1A .catalog.v1.DeleteFamilyResponse\x12H\x0A\x09ListItems\x12\x1C.catalog.v1.ListItemsRequest\x1A\x1D.catalog.v1.ListItemsResponse\x12B\x0A\x07GetItem\x12\x1A.catalog.v1.GetItemRequest\x1A\x1B.catalog.v1.GetItemResponse\x12K\x0A\x0ACreateItem\x12\x1D.catalog.v1.CreateItemRequest\x1A\x1E.catalog.v1.CreateItemResponse\x12K\x0A\x0AUpdateItem\x12\x1D.catalog.v1.UpdateItemRequest\x1A\x1E.catalog.v1.UpdateItemResponse\x12K\x0A\x0ADeleteItem\x12\x1D.catalog.v1.DeleteItemRequest\x1A\x1E.catalog.v1.DeleteItemResponseB<Z:github.com/dudochnicht/proto-gen-go/catalogpb/v1;catalogpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

