<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/manufacturer_service.proto

namespace GPBMetadata\Catalog\V1;

class ManufacturerService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Catalog\V1\Manufacturer::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFC\x0A\x0A%catalog/v1/manufacturer_service.proto\x12\x0Acatalog.v12\x80\x0A\x0A\x13ManufacturerService\x12K\x0A\x0AListBrands\x12\x1D.catalog.v1.ListBrandsRequest\x1A\x1E.catalog.v1.ListBrandsResponse\x12E\x0A\x08GetBrand\x12\x1B.catalog.v1.GetBrandRequest\x1A\x1C.catalog.v1.GetBrandResponse\x12N\x0A\x0BCreateBrand\x12\x1E.catalog.v1.CreateBrandRequest\x1A\x1F.catalog.v1.CreateBrandResponse\x12N\x0A\x0BRenameBrand\x12\x1E.catalog.v1.RenameBrandRequest\x1A\x1F.catalog.v1.RenameBrandResponse\x12N\x0A\x0BDeleteBrand\x12\x1E.catalog.v1.DeleteBrandRequest\x1A\x1F.catalog.v1.DeleteBrandResponse\x12K\x0A\x0AListSeries\x12\x1D.catalog.v1.ListSeriesRequest\x1A\x1E.catalog.v1.ListSeriesResponse\x12E\x0A\x08GetSerie\x12\x1B.catalog.v1.GetSerieRequest\x1A\x1C.catalog.v1.GetSerieResponse\x12N\x0A\x0BCreateSerie\x12\x1E.catalog.v1.CreateSerieRequest\x1A\x1F.catalog.v1.CreateSerieResponse\x12N\x0A\x0BRenameSerie\x12\x1E.catalog.v1.RenameSerieRequest\x1A\x1F.catalog.v1.RenameSerieResponse\x12N\x0A\x0BDeleteSerie\x12\x1E.catalog.v1.DeleteSerieRequest\x1A\x1F.catalog.v1.DeleteSerieResponse\x12K\x0A\x0AListModels\x12\x1D.catalog.v1.ListModelsRequest\x1A\x1E.catalog.v1.ListModelsResponse\x12E\x0A\x08GetModel\x12\x1B.catalog.v1.GetModelRequest\x1A\x1C.catalog.v1.GetModelResponse\x12N\x0A\x0BCreateModel\x12\x1E.catalog.v1.CreateModelRequest\x1A\x1F.catalog.v1.CreateModelResponse\x12N\x0A\x0BRenameModel\x12\x1E.catalog.v1.RenameModelRequest\x1A\x1F.catalog.v1.RenameModelResponse\x12N\x0A\x0BDeleteModel\x12\x1E.catalog.v1.DeleteModelRequest\x1A\x1F.catalog.v1.DeleteModelResponse\x12]\x0A\x10GetFullModelName\x12#.catalog.v1.GetFullModelNameRequest\x1A\$.catalog.v1.GetFullModelNameResponseB<Z:github.com/dudochnicht/proto-gen-go/catalogpb/v1;catalogpbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

