<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.ConfigurationSetting</code>
 */
class ConfigurationSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     */
    protected $component_id = '';
    /**
     * Generated from protobuf field <code>string item_id = 2 [json_name = "itemId"];</code>
     */
    protected $item_id = '';
    /**
     * Generated from protobuf field <code>int32 slot_number = 3 [json_name = "slotNumber"];</code>
     */
    protected $slot_number = 0;
    /**
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     */
    protected $note = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $component_id
     *     @type string $item_id
     *     @type int $slot_number
     *     @type string $note
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @return string
     */
    public function getComponentId()
    {
        return $this->component_id;
    }

    /**
     * Generated from protobuf field <code>string component_id = 1 [json_name = "componentId"];</code>
     * @param string $var
     * @return $this
     */
    public function setComponentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_id = 2 [json_name = "itemId"];</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>string item_id = 2 [json_name = "itemId"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slot_number = 3 [json_name = "slotNumber"];</code>
     * @return int
     */
    public function getSlotNumber()
    {
        return $this->slot_number;
    }

    /**
     * Generated from protobuf field <code>int32 slot_number = 3 [json_name = "slotNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setSlotNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->slot_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

}

