<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.GetConfigurationRequest</code>
 */
class GetConfigurationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     */
    protected $configuration_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configuration_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @return string
     */
    public function getConfigurationId()
    {
        return $this->configuration_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_id = $var;

        return $this;
    }

}

