<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.GetConfigurationResponse</code>
 */
class GetConfigurationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.configuration.v1.Configuration configuration = 1 [json_name = "configuration"];</code>
     */
    protected $configuration = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Configuration\V1\Configuration $configuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.configuration.v1.Configuration configuration = 1 [json_name = "configuration"];</code>
     * @return \Configuration\V1\Configuration|null
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    public function hasConfiguration()
    {
        return isset($this->configuration);
    }

    public function clearConfiguration()
    {
        unset($this->configuration);
    }

    /**
     * Generated from protobuf field <code>.configuration.v1.Configuration configuration = 1 [json_name = "configuration"];</code>
     * @param \Configuration\V1\Configuration $var
     * @return $this
     */
    public function setConfiguration($var)
    {
        GPBUtil::checkMessage($var, \Configuration\V1\Configuration::class);
        $this->configuration = $var;

        return $this;
    }

}

