<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.ListConfigurationsResponse</code>
 */
class ListConfigurationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Configuration configurations = 1 [json_name = "configurations"];</code>
     */
    private $configurations;
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     */
    protected $page_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Configuration\V1\Configuration[] $configurations
     *     @type \Types\V1\OffsetPageResult $page_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Configuration configurations = 1 [json_name = "configurations"];</code>
     * @return RepeatedField<\Configuration\V1\Configuration>
     */
    public function getConfigurations()
    {
        return $this->configurations;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Configuration configurations = 1 [json_name = "configurations"];</code>
     * @param \Configuration\V1\Configuration[] $var
     * @return $this
     */
    public function setConfigurations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Configuration::class);
        $this->configurations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @return \Types\V1\OffsetPageResult|null
     */
    public function getPageResult()
    {
        return $this->page_result;
    }

    public function hasPageResult()
    {
        return isset($this->page_result);
    }

    public function clearPageResult()
    {
        unset($this->page_result);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @param \Types\V1\OffsetPageResult $var
     * @return $this
     */
    public function setPageResult($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPageResult::class);
        $this->page_result = $var;

        return $this;
    }

}

