<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.UpdateConfigurationRequest</code>
 */
class UpdateConfigurationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     */
    protected $configuration_id = '';
    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>string model_id = 3 [json_name = "modelId"];</code>
     */
    protected $model_id = '';
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.ConfigurationSetting configuration_settings = 4 [json_name = "configurationSettings"];</code>
     */
    private $configuration_settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configuration_id
     *     @type string $device_id
     *     @type string $model_id
     *     @type \Configuration\V1\ConfigurationSetting[] $configuration_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @return string
     */
    public function getConfigurationId()
    {
        return $this->configuration_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model_id = 3 [json_name = "modelId"];</code>
     * @return string
     */
    public function getModelId()
    {
        return $this->model_id;
    }

    /**
     * Generated from protobuf field <code>string model_id = 3 [json_name = "modelId"];</code>
     * @param string $var
     * @return $this
     */
    public function setModelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.ConfigurationSetting configuration_settings = 4 [json_name = "configurationSettings"];</code>
     * @return RepeatedField<\Configuration\V1\ConfigurationSetting>
     */
    public function getConfigurationSettings()
    {
        return $this->configuration_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.ConfigurationSetting configuration_settings = 4 [json_name = "configurationSettings"];</code>
     * @param \Configuration\V1\ConfigurationSetting[] $var
     * @return $this
     */
    public function setConfigurationSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\ConfigurationSetting::class);
        $this->configuration_settings = $arr;

        return $this;
    }

}

