<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration/v1/configuration.proto

namespace Configuration\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>configuration.v1.UpdateConfigurationRequest</code>
 */
class UpdateConfigurationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     */
    protected $configuration_id = '';
    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>optional string mainboard_id = 3 [json_name = "mainboardId"];</code>
     */
    protected $mainboard_id = null;
    /**
     * Generated from protobuf field <code>optional string processor_id = 4 [json_name = "processorId"];</code>
     */
    protected $processor_id = null;
    /**
     * Generated from protobuf field <code>optional string graphicscard_internal_id = 5 [json_name = "graphicscardInternalId"];</code>
     */
    protected $graphicscard_internal_id = null;
    /**
     * Generated from protobuf field <code>optional string graphicscard_dedicated_id = 6 [json_name = "graphicscardDedicatedId"];</code>
     */
    protected $graphicscard_dedicated_id = null;
    /**
     * Generated from protobuf field <code>optional string display_id = 7 [json_name = "displayId"];</code>
     */
    protected $display_id = null;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot memory_ids = 8 [json_name = "memoryIds"];</code>
     */
    private $memory_ids;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot storage_ids = 9 [json_name = "storageIds"];</code>
     */
    private $storage_ids;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot connection_ids = 10 [json_name = "connectionIds"];</code>
     */
    private $connection_ids;
    /**
     * Generated from protobuf field <code>optional string keyboard_id = 11 [json_name = "keyboardId"];</code>
     */
    protected $keyboard_id = null;
    /**
     * Generated from protobuf field <code>optional string optical_drive_id = 12 [json_name = "opticalDriveId"];</code>
     */
    protected $optical_drive_id = null;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot power_supply_ids = 13 [json_name = "powerSupplyIds"];</code>
     */
    private $power_supply_ids;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot battery_ids = 14 [json_name = "batteryIds"];</code>
     */
    private $battery_ids;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot additional_hardware_ids = 15 [json_name = "additionalHardwareIds"];</code>
     */
    private $additional_hardware_ids;
    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot attachment_ids = 16 [json_name = "attachmentIds"];</code>
     */
    private $attachment_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $configuration_id
     *     @type string $device_id
     *     @type string $mainboard_id
     *     @type string $processor_id
     *     @type string $graphicscard_internal_id
     *     @type string $graphicscard_dedicated_id
     *     @type string $display_id
     *     @type \Configuration\V1\Slot[] $memory_ids
     *     @type \Configuration\V1\Slot[] $storage_ids
     *     @type \Configuration\V1\Slot[] $connection_ids
     *     @type string $keyboard_id
     *     @type string $optical_drive_id
     *     @type \Configuration\V1\Slot[] $power_supply_ids
     *     @type \Configuration\V1\Slot[] $battery_ids
     *     @type \Configuration\V1\Slot[] $additional_hardware_ids
     *     @type \Configuration\V1\Slot[] $attachment_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Configuration\V1\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @return string
     */
    public function getConfigurationId()
    {
        return $this->configuration_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 1 [json_name = "configurationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string mainboard_id = 3 [json_name = "mainboardId"];</code>
     * @return string
     */
    public function getMainboardId()
    {
        return isset($this->mainboard_id) ? $this->mainboard_id : '';
    }

    public function hasMainboardId()
    {
        return isset($this->mainboard_id);
    }

    public function clearMainboardId()
    {
        unset($this->mainboard_id);
    }

    /**
     * Generated from protobuf field <code>optional string mainboard_id = 3 [json_name = "mainboardId"];</code>
     * @param string $var
     * @return $this
     */
    public function setMainboardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mainboard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string processor_id = 4 [json_name = "processorId"];</code>
     * @return string
     */
    public function getProcessorId()
    {
        return isset($this->processor_id) ? $this->processor_id : '';
    }

    public function hasProcessorId()
    {
        return isset($this->processor_id);
    }

    public function clearProcessorId()
    {
        unset($this->processor_id);
    }

    /**
     * Generated from protobuf field <code>optional string processor_id = 4 [json_name = "processorId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProcessorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->processor_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string graphicscard_internal_id = 5 [json_name = "graphicscardInternalId"];</code>
     * @return string
     */
    public function getGraphicscardInternalId()
    {
        return isset($this->graphicscard_internal_id) ? $this->graphicscard_internal_id : '';
    }

    public function hasGraphicscardInternalId()
    {
        return isset($this->graphicscard_internal_id);
    }

    public function clearGraphicscardInternalId()
    {
        unset($this->graphicscard_internal_id);
    }

    /**
     * Generated from protobuf field <code>optional string graphicscard_internal_id = 5 [json_name = "graphicscardInternalId"];</code>
     * @param string $var
     * @return $this
     */
    public function setGraphicscardInternalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->graphicscard_internal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string graphicscard_dedicated_id = 6 [json_name = "graphicscardDedicatedId"];</code>
     * @return string
     */
    public function getGraphicscardDedicatedId()
    {
        return isset($this->graphicscard_dedicated_id) ? $this->graphicscard_dedicated_id : '';
    }

    public function hasGraphicscardDedicatedId()
    {
        return isset($this->graphicscard_dedicated_id);
    }

    public function clearGraphicscardDedicatedId()
    {
        unset($this->graphicscard_dedicated_id);
    }

    /**
     * Generated from protobuf field <code>optional string graphicscard_dedicated_id = 6 [json_name = "graphicscardDedicatedId"];</code>
     * @param string $var
     * @return $this
     */
    public function setGraphicscardDedicatedId($var)
    {
        GPBUtil::checkString($var, True);
        $this->graphicscard_dedicated_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string display_id = 7 [json_name = "displayId"];</code>
     * @return string
     */
    public function getDisplayId()
    {
        return isset($this->display_id) ? $this->display_id : '';
    }

    public function hasDisplayId()
    {
        return isset($this->display_id);
    }

    public function clearDisplayId()
    {
        unset($this->display_id);
    }

    /**
     * Generated from protobuf field <code>optional string display_id = 7 [json_name = "displayId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayId($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot memory_ids = 8 [json_name = "memoryIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getMemoryIds()
    {
        return $this->memory_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot memory_ids = 8 [json_name = "memoryIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setMemoryIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->memory_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot storage_ids = 9 [json_name = "storageIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getStorageIds()
    {
        return $this->storage_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot storage_ids = 9 [json_name = "storageIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setStorageIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->storage_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot connection_ids = 10 [json_name = "connectionIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getConnectionIds()
    {
        return $this->connection_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot connection_ids = 10 [json_name = "connectionIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setConnectionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->connection_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string keyboard_id = 11 [json_name = "keyboardId"];</code>
     * @return string
     */
    public function getKeyboardId()
    {
        return isset($this->keyboard_id) ? $this->keyboard_id : '';
    }

    public function hasKeyboardId()
    {
        return isset($this->keyboard_id);
    }

    public function clearKeyboardId()
    {
        unset($this->keyboard_id);
    }

    /**
     * Generated from protobuf field <code>optional string keyboard_id = 11 [json_name = "keyboardId"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyboardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyboard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string optical_drive_id = 12 [json_name = "opticalDriveId"];</code>
     * @return string
     */
    public function getOpticalDriveId()
    {
        return isset($this->optical_drive_id) ? $this->optical_drive_id : '';
    }

    public function hasOpticalDriveId()
    {
        return isset($this->optical_drive_id);
    }

    public function clearOpticalDriveId()
    {
        unset($this->optical_drive_id);
    }

    /**
     * Generated from protobuf field <code>optional string optical_drive_id = 12 [json_name = "opticalDriveId"];</code>
     * @param string $var
     * @return $this
     */
    public function setOpticalDriveId($var)
    {
        GPBUtil::checkString($var, True);
        $this->optical_drive_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot power_supply_ids = 13 [json_name = "powerSupplyIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getPowerSupplyIds()
    {
        return $this->power_supply_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot power_supply_ids = 13 [json_name = "powerSupplyIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setPowerSupplyIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->power_supply_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot battery_ids = 14 [json_name = "batteryIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getBatteryIds()
    {
        return $this->battery_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot battery_ids = 14 [json_name = "batteryIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setBatteryIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->battery_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot additional_hardware_ids = 15 [json_name = "additionalHardwareIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getAdditionalHardwareIds()
    {
        return $this->additional_hardware_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot additional_hardware_ids = 15 [json_name = "additionalHardwareIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setAdditionalHardwareIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->additional_hardware_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot attachment_ids = 16 [json_name = "attachmentIds"];</code>
     * @return RepeatedField<\Configuration\V1\Slot>
     */
    public function getAttachmentIds()
    {
        return $this->attachment_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .configuration.v1.Slot attachment_ids = 16 [json_name = "attachmentIds"];</code>
     * @param \Configuration\V1\Slot[] $var
     * @return $this
     */
    public function setAttachmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Configuration\V1\Slot::class);
        $this->attachment_ids = $arr;

        return $this;
    }

}

