<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.CreateInventoryRequest</code>
 */
class CreateInventoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     */
    protected $inventory_type = 0;
    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     */
    protected $component_id = '';
    /**
     * Generated from protobuf field <code>string family_id = 3 [json_name = "familyId"];</code>
     */
    protected $family_id = '';
    /**
     * Generated from protobuf field <code>string item_id = 4 [json_name = "itemId"];</code>
     */
    protected $item_id = '';
    /**
     * Generated from protobuf field <code>optional string note = 5 [json_name = "note"];</code>
     */
    protected $note = null;
    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_from = 6 [json_name = "transferFrom"];</code>
     */
    protected $transfer_from = null;
    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_to = 7 [json_name = "transferTo"];</code>
     */
    protected $transfer_to = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $inventory_type
     *     @type string $component_id
     *     @type string $family_id
     *     @type string $item_id
     *     @type string $note
     *     @type \Inventory\V1\Transfer $transfer_from
     *     @type \Inventory\V1\Transfer $transfer_to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     * @return int
     */
    public function getInventoryType()
    {
        return $this->inventory_type;
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     * @param int $var
     * @return $this
     */
    public function setInventoryType($var)
    {
        GPBUtil::checkEnum($var, \Inventory\V1\InventoryType::class);
        $this->inventory_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     * @return string
     */
    public function getComponentId()
    {
        return $this->component_id;
    }

    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     * @param string $var
     * @return $this
     */
    public function setComponentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string family_id = 3 [json_name = "familyId"];</code>
     * @return string
     */
    public function getFamilyId()
    {
        return $this->family_id;
    }

    /**
     * Generated from protobuf field <code>string family_id = 3 [json_name = "familyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setFamilyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->family_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_id = 4 [json_name = "itemId"];</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>string item_id = 4 [json_name = "itemId"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string note = 5 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return isset($this->note) ? $this->note : '';
    }

    public function hasNote()
    {
        return isset($this->note);
    }

    public function clearNote()
    {
        unset($this->note);
    }

    /**
     * Generated from protobuf field <code>optional string note = 5 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_from = 6 [json_name = "transferFrom"];</code>
     * @return \Inventory\V1\Transfer|null
     */
    public function getTransferFrom()
    {
        return $this->transfer_from;
    }

    public function hasTransferFrom()
    {
        return isset($this->transfer_from);
    }

    public function clearTransferFrom()
    {
        unset($this->transfer_from);
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_from = 6 [json_name = "transferFrom"];</code>
     * @param \Inventory\V1\Transfer $var
     * @return $this
     */
    public function setTransferFrom($var)
    {
        GPBUtil::checkMessage($var, \Inventory\V1\Transfer::class);
        $this->transfer_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_to = 7 [json_name = "transferTo"];</code>
     * @return \Inventory\V1\Transfer|null
     */
    public function getTransferTo()
    {
        return $this->transfer_to;
    }

    public function hasTransferTo()
    {
        return isset($this->transfer_to);
    }

    public function clearTransferTo()
    {
        unset($this->transfer_to);
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.Transfer transfer_to = 7 [json_name = "transferTo"];</code>
     * @param \Inventory\V1\Transfer $var
     * @return $this
     */
    public function setTransferTo($var)
    {
        GPBUtil::checkMessage($var, \Inventory\V1\Transfer::class);
        $this->transfer_to = $var;

        return $this;
    }

}

