<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.CreateInventoryRequest</code>
 */
class CreateInventoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     */
    protected $inventory_type = 0;
    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     */
    protected $component_id = '';
    /**
     * Generated from protobuf field <code>string item_id = 3 [json_name = "itemId"];</code>
     */
    protected $item_id = '';
    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     */
    protected $note = null;
    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     */
    protected $transaction_ids = null;
    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference from_device = 6 [json_name = "fromDevice"];</code>
     */
    protected $from_device = null;
    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference to_device = 7 [json_name = "toDevice"];</code>
     */
    protected $to_device = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $inventory_type
     *     @type string $component_id
     *     @type string $item_id
     *     @type string $note
     *     @type \Device\V1\TransactionIds $transaction_ids
     *     @type \Inventory\V1\DeviceReference $from_device
     *     @type \Inventory\V1\DeviceReference $to_device
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     * @return int
     */
    public function getInventoryType()
    {
        return $this->inventory_type;
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.InventoryType inventory_type = 1 [json_name = "inventoryType"];</code>
     * @param int $var
     * @return $this
     */
    public function setInventoryType($var)
    {
        GPBUtil::checkEnum($var, \Inventory\V1\InventoryType::class);
        $this->inventory_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     * @return string
     */
    public function getComponentId()
    {
        return $this->component_id;
    }

    /**
     * Generated from protobuf field <code>string component_id = 2 [json_name = "componentId"];</code>
     * @param string $var
     * @return $this
     */
    public function setComponentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_id = 3 [json_name = "itemId"];</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>string item_id = 3 [json_name = "itemId"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return isset($this->note) ? $this->note : '';
    }

    public function hasNote()
    {
        return isset($this->note);
    }

    public function clearNote()
    {
        unset($this->note);
    }

    /**
     * Generated from protobuf field <code>optional string note = 4 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     * @return \Device\V1\TransactionIds|null
     */
    public function getTransactionIds()
    {
        return $this->transaction_ids;
    }

    public function hasTransactionIds()
    {
        return isset($this->transaction_ids);
    }

    public function clearTransactionIds()
    {
        unset($this->transaction_ids);
    }

    /**
     * Generated from protobuf field <code>.device.v1.TransactionIds transaction_ids = 5 [json_name = "transactionIds"];</code>
     * @param \Device\V1\TransactionIds $var
     * @return $this
     */
    public function setTransactionIds($var)
    {
        GPBUtil::checkMessage($var, \Device\V1\TransactionIds::class);
        $this->transaction_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference from_device = 6 [json_name = "fromDevice"];</code>
     * @return \Inventory\V1\DeviceReference|null
     */
    public function getFromDevice()
    {
        return $this->from_device;
    }

    public function hasFromDevice()
    {
        return isset($this->from_device);
    }

    public function clearFromDevice()
    {
        unset($this->from_device);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference from_device = 6 [json_name = "fromDevice"];</code>
     * @param \Inventory\V1\DeviceReference $var
     * @return $this
     */
    public function setFromDevice($var)
    {
        GPBUtil::checkMessage($var, \Inventory\V1\DeviceReference::class);
        $this->from_device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference to_device = 7 [json_name = "toDevice"];</code>
     * @return \Inventory\V1\DeviceReference|null
     */
    public function getToDevice()
    {
        return $this->to_device;
    }

    public function hasToDevice()
    {
        return isset($this->to_device);
    }

    public function clearToDevice()
    {
        unset($this->to_device);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.DeviceReference to_device = 7 [json_name = "toDevice"];</code>
     * @param \Inventory\V1\DeviceReference $var
     * @return $this
     */
    public function setToDevice($var)
    {
        GPBUtil::checkMessage($var, \Inventory\V1\DeviceReference::class);
        $this->to_device = $var;

        return $this;
    }

}

