<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.DeleteInventoryRequest</code>
 */
class DeleteInventoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string inventory_id = 1 [json_name = "inventoryId"];</code>
     */
    protected $inventory_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $inventory_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string inventory_id = 1 [json_name = "inventoryId"];</code>
     * @return string
     */
    public function getInventoryId()
    {
        return $this->inventory_id;
    }

    /**
     * Generated from protobuf field <code>string inventory_id = 1 [json_name = "inventoryId"];</code>
     * @param string $var
     * @return $this
     */
    public function setInventoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->inventory_id = $var;

        return $this;
    }

}

