<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.DeviceReference</code>
 */
class DeviceReference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     */
    protected $configuration_id = '';
    /**
     * Generated from protobuf field <code>optional string transaction_id = 3 [json_name = "transactionId"];</code>
     */
    protected $transaction_id = null;
    /**
     * Generated from protobuf field <code>int32 slot_number = 4 [json_name = "slotNumber"];</code>
     */
    protected $slot_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type string $configuration_id
     *     @type string $transaction_id
     *     @type int $slot_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     * @return string
     */
    public function getConfigurationId()
    {
        return $this->configuration_id;
    }

    /**
     * Generated from protobuf field <code>string configuration_id = 2 [json_name = "configurationId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConfigurationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->configuration_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 3 [json_name = "transactionId"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return isset($this->transaction_id) ? $this->transaction_id : '';
    }

    public function hasTransactionId()
    {
        return isset($this->transaction_id);
    }

    public function clearTransactionId()
    {
        unset($this->transaction_id);
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 3 [json_name = "transactionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slot_number = 4 [json_name = "slotNumber"];</code>
     * @return int
     */
    public function getSlotNumber()
    {
        return $this->slot_number;
    }

    /**
     * Generated from protobuf field <code>int32 slot_number = 4 [json_name = "slotNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setSlotNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->slot_number = $var;

        return $this;
    }

}

