<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.GetDeviceInventoriesRequest</code>
 */
class GetDeviceInventoriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>optional .inventory.v1.TransferDirection transfer_direction = 2 [json_name = "transferDirection"];</code>
     */
    protected $transfer_direction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type int $transfer_direction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.TransferDirection transfer_direction = 2 [json_name = "transferDirection"];</code>
     * @return int
     */
    public function getTransferDirection()
    {
        return isset($this->transfer_direction) ? $this->transfer_direction : 0;
    }

    public function hasTransferDirection()
    {
        return isset($this->transfer_direction);
    }

    public function clearTransferDirection()
    {
        unset($this->transfer_direction);
    }

    /**
     * Generated from protobuf field <code>optional .inventory.v1.TransferDirection transfer_direction = 2 [json_name = "transferDirection"];</code>
     * @param int $var
     * @return $this
     */
    public function setTransferDirection($var)
    {
        GPBUtil::checkEnum($var, \Inventory\V1\TransferDirection::class);
        $this->transfer_direction = $var;

        return $this;
    }

}

