<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.GetInventoryResponse</code>
 */
class GetInventoryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.inventory.v1.Inventory inventory = 1 [json_name = "inventory"];</code>
     */
    protected $inventory = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inventory\V1\Inventory $inventory
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.Inventory inventory = 1 [json_name = "inventory"];</code>
     * @return \Inventory\V1\Inventory|null
     */
    public function getInventory()
    {
        return $this->inventory;
    }

    public function hasInventory()
    {
        return isset($this->inventory);
    }

    public function clearInventory()
    {
        unset($this->inventory);
    }

    /**
     * Generated from protobuf field <code>.inventory.v1.Inventory inventory = 1 [json_name = "inventory"];</code>
     * @param \Inventory\V1\Inventory $var
     * @return $this
     */
    public function setInventory($var)
    {
        GPBUtil::checkMessage($var, \Inventory\V1\Inventory::class);
        $this->inventory = $var;

        return $this;
    }

}

