<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inventory.v1.ListInventoriesResponse</code>
 */
class ListInventoriesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .inventory.v1.Inventory inventories = 1 [json_name = "inventories"];</code>
     */
    private $inventories;
    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     */
    protected $page_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inventory\V1\Inventory[] $inventories
     *     @type \Types\V1\OffsetPageResult $page_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .inventory.v1.Inventory inventories = 1 [json_name = "inventories"];</code>
     * @return RepeatedField<\Inventory\V1\Inventory>
     */
    public function getInventories()
    {
        return $this->inventories;
    }

    /**
     * Generated from protobuf field <code>repeated .inventory.v1.Inventory inventories = 1 [json_name = "inventories"];</code>
     * @param \Inventory\V1\Inventory[] $var
     * @return $this
     */
    public function setInventories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inventory\V1\Inventory::class);
        $this->inventories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @return \Types\V1\OffsetPageResult|null
     */
    public function getPageResult()
    {
        return $this->page_result;
    }

    public function hasPageResult()
    {
        return isset($this->page_result);
    }

    public function clearPageResult()
    {
        unset($this->page_result);
    }

    /**
     * Generated from protobuf field <code>.types.v1.OffsetPageResult page_result = 2 [json_name = "pageResult"];</code>
     * @param \Types\V1\OffsetPageResult $var
     * @return $this
     */
    public function setPageResult($var)
    {
        GPBUtil::checkMessage($var, \Types\V1\OffsetPageResult::class);
        $this->page_result = $var;

        return $this;
    }

}

