<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace Inventory\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>inventory.v1.TransferDirection</code>
 */
class TransferDirection
{
    /**
     * Generated from protobuf enum <code>TRANSFER_DIRECTION_UNSPECIFIED = 0;</code>
     */
    const TRANSFER_DIRECTION_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TRANSFER_DIRECTION_FROM = 1;</code>
     */
    const TRANSFER_DIRECTION_FROM = 1;
    /**
     * Generated from protobuf enum <code>TRANSFER_DIRECTION_TO = 2;</code>
     */
    const TRANSFER_DIRECTION_TO = 2;

    private static $valueToName = [
        self::TRANSFER_DIRECTION_UNSPECIFIED => 'TRANSFER_DIRECTION_UNSPECIFIED',
        self::TRANSFER_DIRECTION_FROM => 'TRANSFER_DIRECTION_FROM',
        self::TRANSFER_DIRECTION_TO => 'TRANSFER_DIRECTION_TO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

