<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo/v1/geo.proto

namespace GPBMetadata\Geo\V1;

class Geo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ao\x0A\x10geo/v1/geo.proto\x12\x06geo.v1\"\x15\x0A\x03Geo\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02idB4Z2github.com/dudochnicht/proto-gen-go/geopb/v1;geopbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

