<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory_service.proto

namespace GPBMetadata\Inventory\V1;

class InventoryService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Inventory\V1\Inventory::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDD\x06\x0A\$inventory/v1/inventory_service.proto\x12\x0Cinventory.v12\xDC\x05\x0A\x10InventoryService\x12v\x0A\x17FindInventoriesByDevice\x12,.inventory.v1.FindInventoriesByDeviceRequest\x1A-.inventory.v1.FindInventoriesByDeviceResponse\x12y\x0A\x18FindAvailableInventories\x12-.inventory.v1.FindAvailableInventoriesRequest\x1A..inventory.v1.FindAvailableInventoriesResponse\x12^\x0A\x0FListInventories\x12\$.inventory.v1.ListInventoriesRequest\x1A%.inventory.v1.ListInventoriesResponse\x12U\x0A\x0CGetInventory\x12!.inventory.v1.GetInventoryRequest\x1A\".inventory.v1.GetInventoryResponse\x12^\x0A\x0FCreateInventory\x12\$.inventory.v1.CreateInventoryRequest\x1A%.inventory.v1.CreateInventoryResponse\x12^\x0A\x0FUpdateInventory\x12\$.inventory.v1.UpdateInventoryRequest\x1A%.inventory.v1.UpdateInventoryResponse\x12^\x0A\x0FDeleteInventory\x12\$.inventory.v1.DeleteInventoryRequest\x1A%.inventory.v1.DeleteInventoryResponseB@Z>github.com/dudochnicht/proto-gen-go/inventorypb/v1;inventorypbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

