<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto

namespace GPBMetadata\Inventory\V1;

class Inventory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x93\x01\x0A\x1Cinventory/v1/inventory.proto\x12\x0Cinventory.v1\"\x1B\x0A\x09Inventory\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02idB@Z>github.com/dudochnicht/proto-gen-go/inventorypb/v1;inventorypbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

